### ISSUE TITLE
'Node' object has no attribute 'through_tables'

### ISSUE THREAD

**Issue by tmendesilva** [toluaina/pgsync#105]
PGSync version: 1.1.32
Postgres version:  10.2 
Elasticsearch version: 7.2
Redis version: 6.2.1
Python version:  3.8

Problem Description: 
Bootstrap is ok, but when run pgsync got this error

sql schema:

```
CREATE TABLE treatment(
    treatment_id SERIAL PRIMARY KEY,
   ....
);

CREATE TABLE treatment_marker (
    treatment_marker_id SERIAL PRIMARY KEY,
    treatment_marker_name VARCHAR(50) NOT NULL,
    treatment_marker_initials VARCHAR(5) UNIQUE NOT NULL,
    treatment_marker_color VARCHAR(15) NOT NULL,
    treatment_marker_background_color VARCHAR(15) NOT NULL,
    ...
);

CREATE TABLE treatment_has_treatment_marker (
    treatment_id INTEGER NOT NULL,
    treatment_marker_id INTEGER NOT NULL,
    created_by INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    PRIMARY KEY(treatment_id, treatment_marker_id),
    FOREIGN KEY(treatment_id) REFERENCES treatment(treatment_id),
    FOREIGN KEY(treatment_marker_id) REFERENCES treatment_marker(treatment_marker_id)
);
```

schema.json 
```
[
	{
		"database": "aptassaude_diagnosticcenter23",
		"index": "schedule",
		"nodes": [
			{
				"table": "schedule",
				"columns": [
					"schedule_id",
					"schedule_group_id",
					"when",
					"when_end",
					"confirmed",
					"patient_id",
					"health_facility_id",
					"health_professional_id",
					"health_insurance_company_id",
					"health_insurance_company_plan_id",
					"internal_health_facility_type",
					"observation"
				],
				"transform": {
					"rename": {
						"health_facility_id": "hf_id",
						"health_professional_id": "rhp_id",
						"health_insurance_company_id": "hic_id",
						"health_insurance_company_plan_id": "hicp_id"
					}
				},
				"children": [
					{
						"table": "schedule_group",
						"columns": [
							"schedule_group_name",
							"schedule_group_color"
						],
						"relationship": {
							"variant": "scalar",
							"type": "one_to_one"
						}
					},
					{
						"table": "treatment",
						"relationship": {
							"variant": "object",
							"type": "one_to_one"
						},
						"columns": [
							"treatment_id",
							"treatment_status_id",
							"signed",
							"released",
							"treatment_id_by_pacs",
							"created_at",
							"external_treatment_code",
							"external_treatment_number",
							"treatment_character_code",
							"deadline_date",
							"ended_at",
							"study_instance_uid_by_pacs",
							"signature_conclusion_date",
							"contrast",
							"contrast_dosage"
						],
						"children": [
							{
								"table": "treatment_marker",
								"relationship": {
									"type": "one_to_many",
									"variant": "object",
									"through_tables": [
										"treatment_has_treatment_marker"
									]
								},
								"columns": [
									"treatment_marker_id",
									"treatment_marker_initials",
									"treatment_marker_name",
									"treatment_marker_color",
									"treatment_marker_background_color"
								]
							}
						]
					},
					{
						"table": "patient_has_health_insurance_company_plan",
						"columns": [],
						"relationship": {
							"variant": "scalar",
							"type": "one_to_one"
						},
						"children": [
							{
								"table": "patient",
								"columns": [],
								"relationship": {
									"variant": "scalar",
									"type": "one_to_one"
								},
								"children": [
									{
										"table": "person",
										"relationship": {
											"variant": "object",
											"type": "one_to_one"
										},
										"columns": [
											"person_id",
											"full_name",
											"birthdate",
											"gender",
											"image_path"
										],
										"transform": {
											"rename": {
												"person_id": "ppe_id",
												"full_name": "patient_name"
											}
										}
									}
								]
							}
						]
					}
				]
			}
		]
	}
]

```

Error Message (if any): 

```
Traceback (most recent call last):
$  **pgsync -vc /dados/elastic-stack/schema.json** 
pg_settings:
SELECT setting
FROM pg_settings
WHERE name = 'max_replication_slots'pg_settings:
SELECT setting
FROM pg_settings
WHERE name = 'wal_level'pg_settings:
SELECT setting
FROM pg_settings
WHERE name = 'rds.logical_replication'has_permission:
SELECT usesuper
FROM pg_user
WHERE usename = 'pgsql'
  AND usesuper = TRUE - schedule
   |- schedule_group
   |- treatment
   |   - treatment_marker
    - patient_has_health_insurance_company_plan
       - patient
          - person
Outer subquery:
SELECT CAST(JSON_BUILD_OBJECT('treatment_marker', JSON_BUILD_ARRAY(JSON_BUILD_OBJECT('treatment_marker_id', JSON_BUILD_ARRAY(treatment_marker_1.treatment_marker_id)))) AS JSONB) AS _keys,
       JSON_BUILD_OBJECT('treatment_marker_id', treatment_marker_1.treatment_marker_id, 'treatment_marker_initials', treatment_marker_1.treatment_marker_initials, 'treatment_marker_name', treatment_marker_1.treatment_marker_name, 'treatment_marker_color', treatment_marker_1.treatment_marker_color, 'treatment_marker_background_color', treatment_marker_1.treatment_marker_background_color) AS anon,
       treatment_marker_1.treatment_marker_id
FROM public.treatment_marker AS treatment_marker_1Inner subquery:
SELECT JSON_AGG(CAST(anon_1._keys AS JSONB) || CAST(JSON_BUILD_OBJECT('treatment_has_treatment_marker', JSON_BUILD_ARRAY(JSON_BUILD_OBJECT('treatment_id', JSON_BUILD_ARRAY(treatment_has_treatment_marker_1.treatment_id)), JSON_BUILD_OBJECT('treatment_marker_id', JSON_BUILD_ARRAY(treatment_has_treatment_marker_1.treatment_marker_id)))) AS JSONB)) AS _keys,
       JSON_AGG(anon_1.anon) AS treatment_marker,
       treatment_has_treatment_marker_1.treatment_id
FROM
  (SELECT CAST(JSON_BUILD_OBJECT('treatment_marker', JSON_BUILD_ARRAY(JSON_BUILD_OBJECT('treatment_marker_id', JSON_BUILD_ARRAY(treatment_marker_1.treatment_marker_id)))) AS JSONB) AS _keys,
          JSON_BUILD_OBJECT('treatment_marker_id', treatment_marker_1.treatment_marker_id, 'treatment_marker_initials', treatment_marker_1.treatment_marker_initials, 'treatment_marker_name', treatment_marker_1.treatment_marker_name, 'treatment_marker_color', treatment_marker_1.treatment_marker_color, 'treatment_marker_background_color', treatment_marker_1.treatment_marker_background_color) AS anon,
          treatment_marker_1.treatment_marker_id AS treatment_marker_id
   FROM public.treatment_marker AS treatment_marker_1) AS anon_1,
     public.treatment_has_treatment_marker AS treatment_has_treatment_marker_1Combined subquery:
SELECT JSON_AGG(CAST(anon_1._keys AS JSONB) || CAST(JSON_BUILD_OBJECT('treatment_has_treatment_marker', JSON_BUILD_ARRAY(JSON_BUILD_OBJECT('treatment_id', JSON_BUILD_ARRAY(treatment_has_treatment_marker_1.treatment_id)), JSON_BUILD_OBJECT('treatment_marker_id', JSON_BUILD_ARRAY(treatment_has_treatment_marker_1.treatment_marker_id)))) AS JSONB)) AS _keys,
       JSON_AGG(anon_1.anon) AS treatment_marker,
       treatment_has_treatment_marker_1.treatment_id
FROM public.treatment_has_treatment_marker AS treatment_has_treatment_marker_1
LEFT OUTER JOIN
  (SELECT CAST(JSON_BUILD_OBJECT('treatment_marker', JSON_BUILD_ARRAY(JSON_BUILD_OBJECT('treatment_marker_id', JSON_BUILD_ARRAY(treatment_marker_1.treatment_marker_id)))) AS JSONB) AS _keys,
          JSON_BUILD_OBJECT('treatment_marker_id', treatment_marker_1.treatment_marker_id, 'treatment_marker_initials', treatment_marker_1.treatment_marker_initials, 'treatment_marker_name', treatment_marker_1.treatment_marker_name, 'treatment_marker_color', treatment_marker_1.treatment_marker_color, 'treatment_marker_background_color', treatment_marker_1.treatment_marker_background_color) AS anon,
          treatment_marker_1.treatment_marker_id AS treatment_marker_id
   FROM public.treatment_marker AS treatment_marker_1) AS anon_1 ON anon_1.treatment_marker_id = treatment_has_treatment_marker_1.treatment_marker_id
GROUP BY treatment_has_treatment_marker_1.treatment_id2021-04-17 18:49:19.124:ERROR:pgsync.sync: Exception 'Node' object has no attribute 'through_tables'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pgsync/sync.py", line 669, in _sync
    self.query_builder.build_queries(node)
  File "/usr/lib/python3.8/site-packages/pgsync/querybuilder.py", line 807, in build_queries
    self._non_through(node)
  File "/usr/lib/python3.8/site-packages/pgsync/querybuilder.py", line 614, in _non_through
    foreign_keys = self._get_foreign_keys(node, child)
  File "/usr/lib/python3.8/site-packages/pgsync/querybuilder.py", line 33, in _get_foreign_keys
    if model_a.through_tables:
AttributeError: 'Node' object has no attribute 'through_tables'
2021-04-17 18:49:19.129:ERROR:pgsync.sync: Exception 'Node' object has no attribute 'through_tables'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pgsync/sync.py", line 730, in sync
    self.es.bulk(self.index, docs)
  File "/usr/lib/python3.8/site-packages/pgsync/elastichelper.py", line 80, in bulk
    for _ in parallel_bulk(
  File "/usr/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 454, in parallel_bulk
    for result in pool.imap(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
    for action, data in actions:
  File "/usr/lib/python3.8/site-packages/pgsync/sync.py", line 669, in _sync
    self.query_builder.build_queries(node)
  File "/usr/lib/python3.8/site-packages/pgsync/querybuilder.py", line 807, in build_queries
    self._non_through(node)
  File "/usr/lib/python3.8/site-packages/pgsync/querybuilder.py", line 614, in _non_through
    foreign_keys = self._get_foreign_keys(node, child)
  File "/usr/lib/python3.8/site-packages/pgsync/querybuilder.py", line 33, in _get_foreign_keys
    if model_a.through_tables:
AttributeError: 'Node' object has no attribute 'through_tables'
 0:00:04.270223 (4.27 sec)
Traceback (most recent call last):
  File "/usr/bin/pgsync", line 7, in <module>
    sync.main()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pgsync/sync.py", line 1022, in main
    sync.pull()
  File "/usr/lib/python3.8/site-packages/pgsync/sync.py", line 886, in pull
    self.sync(txmin=txmin, txmax=txmax)
  File "/usr/lib/python3.8/site-packages/pgsync/sync.py", line 730, in sync
    self.es.bulk(self.index, docs)
  File "/usr/lib/python3.8/site-packages/pgsync/elastichelper.py", line 80, in bulk
    for _ in parallel_bulk(
  File "/usr/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 454, in parallel_bulk
    for result in pool.imap(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
    for action, data in actions:
  File "/usr/lib/python3.8/site-packages/pgsync/sync.py", line 669, in _sync
    self.query_builder.build_queries(node)
  File "/usr/lib/python3.8/site-packages/pgsync/querybuilder.py", line 807, in build_queries
    self._non_through(node)
  File "/usr/lib/python3.8/site-packages/pgsync/querybuilder.py", line 614, in _non_through
    foreign_keys = self._get_foreign_keys(node, child)
  File "/usr/lib/python3.8/site-packages/pgsync/querybuilder.py", line 33, in _get_foreign_keys
    if model_a.through_tables:
AttributeError: 'Node' object has no attribute 'through_tables'
```

**Comment by tmendesilva** [comment]
> Hi @tmendesilva, I'm experiencing the same problem right now. Did you manage to solve it in any way?

Not yet, I think it's a bug.

**Comment by toluaina** [comment]
Apologies, this is a bug and is fixed in the master branch. 
I will publish a new release shortly to resolve this.

**Comment by martinhogf** [comment]
Thanks for the quick response!!

Do you have any forecast for this publication to happen?

**Comment by martinhogf** [comment]
Thank you!

**Comment by tmendesilva** [comment]
Tnks

**Comment by martinhogf** [comment]
Hello @toluaina! 
It's OK?
Did everything go well with the tests?

**Comment by kaiquefelipe** [comment]
Hello @toluaina.

I am experiencing the same problem.
When will a new version be published?

**Comment by toluaina** [comment]
I will publish this tomorrow. Sorry abou this

**Comment by toluaina** [comment]
This has now been published.
