### ISSUE TITLE
Book example is not working

### ISSUE THREAD

**Issue by abdheshkumar** [toluaina/pgsync#117]
PGSync version: 1.1.13

Postgres version: debezium/postgres:13-alpine

Elasticsearch version: 7.12

Redis version: latest

Python version: 

Problem Description: Book example is not working and also it is not creating elasticsearch settings

Error Message (if any): 
```
wait-for-it.sh: waiting 60 seconds for postgres:5432
wait-for-it.sh: postgres:5432 is available after 0 seconds
wait-for-it.sh: waiting 60 seconds for elasticsearch:9200
wait-for-it.sh: elasticsearch:9200 is available after 0 seconds
wait-for-it.sh: waiting 60 seconds for redis:6379
wait-for-it.sh: redis:6379 is available after 0 seconds
2021-04-27 23:44:40.864:WARNING:pgsync.helper: Database "book" does not exist: (psycopg2.OperationalError) FATAL:  database "book" does not exist

(Background on this error at: http://sqlalche.me/e/14/e3q8)
2021-04-27 23:44:41,049 INFO sqlalchemy.engine.Engine select version()
2021-04-27 23:44:41,049 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-04-27 23:44:41,050 INFO sqlalchemy.engine.Engine select current_schema()
2021-04-27 23:44:41,050 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-04-27 23:44:41,051 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2021-04-27 23:44:41,051 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-04-27 23:44:41,053 INFO sqlalchemy.engine.Engine CREATE EXTENSION IF NOT EXISTS "POSTGIS"
2021-04-27 23:44:41,053 INFO sqlalchemy.engine.Engine [raw sql] (None,)
2021-04-27 23:44:41,054 INFO sqlalchemy.engine.Engine ROLLBACK using DBAPI connection.rollback(), DBAPI should ignore due to autocommit mode
2021-04-27 23:44:41.054:ERROR:pgsync.base: Exception (psycopg2.errors.UndefinedFile) could not open extension control file "/usr/local/share/postgr
esql/extension/POSTGIS.control": No such file or directory

[SQL: CREATE EXTENSION IF NOT EXISTS "POSTGIS"]
[parameters: (None,)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFile: could not open extension control file "/usr/local/share/postgresql/extension/POSTGIS.control": No such file or direc
tory


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 1084, in pg_execute
    conn.execute(query, values)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1190, in execute
    future=False,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1491, in _exec_driver_sql
    distilled_parameters,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.UndefinedFile) could not open extension control file "/usr/local/share/postgresql/extension/POSTG
IS.control": No such file or directory

[SQL: CREATE EXTENSION IF NOT EXISTS "POSTGIS"]
[parameters: (None,)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFile: could not open extension control file "/usr/local/share/postgresql/extension/POSTGIS.control": No such file or direc
tory


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/book/schema.py", line 275, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "examples/book/schema.py", line 271, in main
    setup(config)
  File "examples/book/schema.py", line 248, in setup
    create_extension(database, 'POSTGIS', echo=True)
  File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 1117, in create_extension
    pg_execute(engine, f'CREATE EXTENSION IF NOT EXISTS "{extension}"')
  File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 1084, in pg_execute
    conn.execute(query, values)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1190, in execute
    future=False,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1491, in _exec_driver_sql
    distilled_parameters,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.UndefinedFile) could not open extension control file "/usr/local/share/postgresql/extension/POSTG
IS.control": No such file or directory

[SQL: CREATE EXTENSION IF NOT EXISTS "POSTGIS"]
[parameters: (None,)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1686, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 909, in do_executemany
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/psycopg2/extras.py", line 1292, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedTable: relation "public.continent" does not exist
LINE 1: INSERT INTO public.continent (name) VALUES ('Europe'),('Nort...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/book/data.py", line 501, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "examples/book/data.py", line 64, in main
    session.add_all(continents.values())
  File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 952, in __exit__
    self.session.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1423, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3255, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3395, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3355, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 453, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    uow,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 247, in save_obj
    insert,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1154, in _emit_insert_statements
    statement, multiparams, execution_options=execution_options
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 314, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1399, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1686, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 909, in do_executemany
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/psycopg2/extras.py", line 1292, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "public.continent" does not exist
LINE 1: INSERT INTO public.continent (name) VALUES ('Europe'),('Nort...
                    ^

[SQL: INSERT INTO public.continent (name) VALUES (%(name)s) RETURNING public.continent.id]
[parameters: ({'name': 'Europe'}, {'name': 'North America'})]
(Background on this error at: http://sqlalche.me/e/14/f405)
Traceback (most recent call last):
  File "/usr/local/bin/bootstrap", line 68, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/bootstrap", line 59, in main
    sync = Sync(document, verbose=verbose, **params)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 80, in __init__
    self.validate()
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 88, in validate
    self._plugins = Plugins('plugins', self.plugins)
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 26, in __init__
    self.reload()
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 33, in reload
    self.walk(self.package)
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 38, in walk
    plugins = importlib.import_module(package)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins'
 0:00:00.023201 (0.02 sec)
Traceback (most recent call last):
  File "/usr/local/bin/pgsync", line 7, in <module>
    sync.main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 1051, in main
    params=params,
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 80, in __init__
    self.validate()
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 88, in validate
    self._plugins = Plugins('plugins', self.plugins)
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 26, in __init__
    self.reload()
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 33, in reload
    self.walk(self.package)
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 38, in walk
    plugins = importlib.import_module(package)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins'

```
`runserver.sh`

```
#! /bin/sh
./wait-for-it.sh postgres:5432 -t 60
./wait-for-it.sh elasticsearch:9200 -t 60
./wait-for-it.sh redis:6379 -t 60

python examples/book/schema.py --config examples/book/schema.json
python examples/book/data.py --config examples/book/schema.json

bootstrap --config examples/book/schema.json
pgsync --config examples/book/schema.json --daemon
```
```


```

**Comment by toluaina** [comment]
Should be working now. Sorry about this
