### ISSUE TITLE
Unable to put two independent tables data into single index

### ISSUE THREAD

**Issue by abdheshkumar** [toluaina/pgsync#118]
PGSync version: latest

Postgres version: latest

Elasticsearch version: latest

Redis version: latest

Python version: latest

Problem Description: 
It is not able to run more than one nodes.

Here is the schema file
```
[
  {
    "database": "productstoredb",
    "index": "portfolio_clusters",
    "nodes": [
      {
        "table": "pm_ptflio_bld_blck_grp",
        "schema": "product_store",
        "columns": [
          "ptflio_bld_blck_grp_mstr_key",
          "ptflio_bld_blck_grp_nm"
        ]
      },
      {
        "table": "pm_ptflio_bld_blck",
        "schema": "product_store",
        "columns": [
          "ptflio_bld_blck_mstr_key",
          "ptflio_bld_blck_nm"
        ]
      }
    ]
  }
]
```
Here are a log pgsync logs
```
- pm_ptflio_bld_blck_grp
- pm_ptflio_bld_blck_grp
 [==================================================] 100.0%
```

The log should display like 

```
- pm_ptflio_bld_blck_grp
- pm_ptflio_bld_blck
 [==================================================] 100.0%
```

Error Message (if any): I am trying to put two independent tables data into a single index but it is synching only the data of the first table which means it is moving `pm_ptflio_bld_blck_grp` data into `portfolio_clusters` index and there is no data in the index for `pm_ptflio_bld_blck` table.

```


```

**Comment by toluaina** [comment]
Sorry for the delay.
Having two or more nodes in the same document was misleading as we only used the first one anyway.
I would suggest only using one node.
The latest master version only supports having a single node.
This is now updated n the [documentation](https://pgsync.com/schema/)

```
[
    {
        "database":"productstoredb",
        "index":"portfolio_clusters",
        "nodes":{
            "table":"pm_ptflio_bld_blck_grp",
            "schema":"product_store",
            "columns":[
                "ptflio_bld_blck_grp_mstr_key",
                "ptflio_bld_blck_grp_nm"
            ]
        }
    }
]
```

**Comment by abdheshkumar** [comment]
@toluaina thank you so much for the update. Will it work with the already released pgsync version?
I am getting the below error with pgsync 1.1.32
```
Traceback (most recent call last):
  File "/usr/local/bin/bootstrap", line 68, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/bootstrap", line 59, in main
    sync = Sync(document, verbose=verbose, **params)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 80, in __init__
    self.validate()
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 131, in validate
    root = self.tree.build(self.nodes[0])
KeyError: 0
 0:00:00.042135 (0.04 sec)
Traceback (most recent call last):
  File "/usr/local/bin/pgsync", line 7, in <module>
    sync.main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 1020, in main
    params=params,
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 80, in __init__
    self.validate()
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 131, in validate
    root = self.tree.build(self.nodes[0])
KeyError: 0
```

**Comment by abdheshkumar** [comment]
@toluaina The actual issue remains the same. For example, I have below schema
```
[
  {
    "database": "productstoredb",
    "index": "portfolio_clusters",
    "nodes": {
      "table": "pm_ptflio_bld_blck_grp",
      "schema": "product_store",
      "columns": [
        "ptflio_bld_blck_grp_mstr_key",
        "ptflio_bld_blck_grp_nm"
      ]
    }
  },
  {
    "database": "productstoredb",
    "index": "portfolio_clusters",
    "nodes": {
      "table": "pm_ptflio_bld_blck",
      "schema": "product_store",
      "columns": [
        "ptflio_bld_blck_mstr_key",
        "ptflio_bld_blck_nm"
      ]
    }
  }
]
```
My requirement is, I want to put two tables of data into a single index but currently, it is putting `pm_ptflio_bld_blck_grp` table data into `portfolio_clusters` cluster.

**Comment by toluaina** [comment]
Are you referring to the docker example? Yes you are right this will throw a KeyError. 
A new version will be released soon. to resolve this later today,

**Comment by abdheshkumar** [comment]
> Are you referring to the docker example? Yes you are right this will throw a KeyError.
> A new version will be released soon. to resolve this later today,

Yes, I was referring to the docker examples.

**Comment by abdheshkumar** [comment]
> @toluaina The actual issue remains the same. For example, I have below schema
> 
> ```
> [
>   {
>     "database": "productstoredb",
>     "index": "portfolio_clusters",
>     "nodes": {
>       "table": "pm_ptflio_bld_blck_grp",
>       "schema": "product_store",
>       "columns": [
>         "ptflio_bld_blck_grp_mstr_key",
>         "ptflio_bld_blck_grp_nm"
>       ]
>     }
>   },
>   {
>     "database": "productstoredb",
>     "index": "portfolio_clusters",
>     "nodes": {
>       "table": "pm_ptflio_bld_blck",
>       "schema": "product_store",
>       "columns": [
>         "ptflio_bld_blck_mstr_key",
>         "ptflio_bld_blck_nm"
>       ]
>     }
>   }
> ]
> ```
> 
> My requirement is, I want to put two tables of data into a single index but currently, it is putting `pm_ptflio_bld_blck_grp` table data into `portfolio_clusters` cluster.

Could you please check if it is possible or not?

**Comment by toluaina** [comment]
- Are the two tables related in any way ?
- If so they should be connected via a [relationship](https://pgsync.com/tutorial/relationship-with-object-variant/) and put into single index.
- If not, then thy should be in separate indices (see example below).
- You need one table to represent the root of your document in Elasticsearch. This is the typical use case.


```
[
    {
        "database": "db1",
        "index": "index1",
        "nodes": {
            "table": "table1",
            "columns": [
            ]
        }
    },
    {
        "database": "db1",
        "index": "index2",
        "nodes": {
            "table": "table2",
            "columns": [
            ]
        }
    }
]
```

**Comment by abdheshkumar** [comment]
@toluaina Both tables are independent of each other  but I want to put both tables of data into a single index

**Comment by toluaina** [comment]
I'm afraid this is not supported. 
For pgsync this represents two different types of query paths so it would be better represented as separate indices.

**Comment by Ebsan** [comment]
I had a similar need, but as @toluaina alluded to it's better/cleaner/easier to do it a different way. What I ended up doing was syncing each table to an index that was named something like <table-name>_shared_index. And then search using a wildcard on the `*_shared_index` index and it'll grab all those indices. 

This is a much cleaner approach and is the preferred way for elasticsearch. Elasticsearch works very well with common data sets in different indices such as with the rolling logs or time series data.

**Comment by abdheshkumar** [comment]
It is nice to have such a feature but I am not sure how much work we will have to do.

**Comment by toluaina** [comment]
Closing this for now. We can consider this as a feature request for future work in needed.
