### ISSUE TITLE
Documentation should show 'nodes' not 'node'

### ISSUE THREAD

**Issue by smokedsalmonbagel** [toluaina/pgsync#121]
PGSync version: 
1.1.33
Postgres version: 

Elasticsearch version: 

Redis version: 

Python version: 

Problem Description: 
This page of the documentation says to use the key 'node' with a  value that is a dictionary:
https://pgsync.com/tutorial/multiple-schemas-in-single-config/
I get the error below.  I believe this should be 'nodes' like:
```
[
    {
        "database": "book",
        "index": "book_index",
        "nodes": [{
            "table": "book"
        }]
    },
    {
        "database": "book",
        "index": "author_index",
        "nodes": [{
            "table": "author"
        }]
    }
]
```

Error Message (if any): 

```
Traceback (most recent call last):
pgsync_1         |   File "/usr/local/bin/bootstrap", line 68, in <module>
pgsync_1         |     main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
pgsync_1         |   File "/usr/local/bin/bootstrap", line 59, in main
pgsync_1         |     sync = Sync(document, verbose=verbose, **params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 80, in __init__
pgsync_1         |     self.validate()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 131, in validate
pgsync_1         |     root = self.tree.build(self.nodes[0])
pgsync_1         | IndexError: list index out of range

```

**Comment by toluaina** [comment]
Sorry about this. I updated the documentation before the release. 
The schema structure has changed in version 2.0. There is a migration procudure detailed in the [release](https://github.com/toluaina/pgsync/releases)

**Comment by smokedsalmonbagel** [comment]
No problem - just wanted to make sure I was writing the schema correctly.

**Comment by toluaina** [comment]
This has been resolved thanks.
