### ISSUE TITLE
Table not specified in node: {}

### ISSUE THREAD

**Issue by tmendesilva** [toluaina/pgsync#123]
schema.json
```
[
	{
		"database": "xxx",
		"index": "schedule",
		"node": {
			"table": "schedule",
			"columns": [
				"schedule_id",
				"schedule_group_id",
				"when",
				"when_end",
				"confirmed",
				"patient_id",
				"health_facility_id",
				"health_professional_id",
				"health_insurance_company_id",
				"health_insurance_company_plan_id",
				"internal_health_facility_type",
				"observation"
			],
			"transform": {
				"rename": {
					"health_facility_id": "hf_id",
					"health_professional_id": "rhp_id",
					"health_insurance_company_id": "hic_id",
					"health_insurance_company_plan_id": "hicp_id"
				}
			},
			"children": [
				{
					"table": "schedule_group",
					"columns": [
						"schedule_group_name",
						"schedule_group_color"
					],
					"relationship": {
						"variant": "object",
						"type": "one_to_one"
					}
				},
				{
					"table": "treatment",
					"relationship": {
						"variant": "object",
						"type": "one_to_one"
					},
					"columns": [
						"treatment_id",
						"treatment_status_id",
						"signed",
						"released",
						"treatment_id_by_pacs",
						"created_at",
						"external_treatment_code",
						"external_treatment_number",
						"treatment_character_code",
						"deadline_date",
						"ended_at",
						"study_instance_uid_by_pacs",
						"signature_conclusion_date",
						"contrast",
						"contrast_dosage"
					],
					"children": [
						{
							"table": "treatment_marker",
							"relationship": {
								"type": "one_to_many",
								"variant": "object",
								"through_tables": [
									"treatment_has_treatment_marker"
								]
							},
							"columns": [
								"treatment_marker_id",
								"treatment_marker_initials",
								"treatment_marker_name",
								"treatment_marker_color",
								"treatment_marker_background_color"
							]
						}
					]
				},
				{
					"table": "patient",
					"relationship": {
						"type": "one_to_one",
						"variant": "object",
						"through_tables": [
							"patient_has_health_insurance_company_plan"
						]
					},
					"columns": [
						"patient_id"
					],
					"children": [
						{
							"table": "person",
							"relationship": {
								"variant": "object",
								"type": "one_to_one"
							},
							"columns": [
								"person_id",
								"full_name",
								"birthdate",
								"gender",
								"image_path"
							],
							"transform": {
								"rename": {
									"person_id": "ppe_id",
									"full_name": "patient_name"
								}
							}
						}
					]
				}
			]
		}
	}
]

```

Error Message (if any): 

```
$ /usr/bin/bootstrap -v -t -c /dados/elastic-stack/schema.json 
pg_settings:
SELECT setting
FROM pg_settings
WHERE name = %(name_1)spg_settings:
SELECT setting
FROM pg_settings
WHERE name = %(name_1)spg_settings:
SELECT setting
FROM pg_settings
WHERE name = %(name_1)shas_permission:
SELECT usesuper
FROM pg_user
WHERE usename = %(usename_1)s
  AND usesuper = TRUETraceback (most recent call last):
  File "/usr/bin/bootstrap", line 68, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/bootstrap", line 59, in main
    sync = Sync(document, verbose=verbose, repl_slots=False, **params)
  File "/usr/lib/python3.8/site-packages/pgsync/sync.py", line 84, in __init__
    self.validate(repl_slots=repl_slots)
  File "/usr/lib/python3.8/site-packages/pgsync/sync.py", line 150, in validate
    root = self.tree.build(self.nodes)
  File "/usr/lib/python3.8/site-packages/pgsync/node.py", line 250, in build
    raise TableNotInNodeError(
pgsync.exc.TableNotInNodeError: 'Table not specified in node: {}'


```

**Comment by toluaina** [comment]
Sorry about the misleading doc. This should be **nodes** with an **s**. I have updated the docs now. just chanfe node to nodes in the schema above

**Comment by tmendesilva** [comment]
> Sorry about the misleading doc. This should be **nodes** with an **s**. I have updated the docs now. just chanfe node to nodes in the schema above

tnks!!!

**Comment by toluaina** [comment]
All resolved now thanks
