### ISSUE TITLE
psycopg2.errors.SyntaxError: syntax error at or near ")"

### ISSUE THREAD

**Issue by andrewtran1995** [toluaina/pgsync#124]
## Environment
* PGSync version: `2.0.0`
* Postgres version: `10.16`
* Elasticsearch version: `7.12.1`
* Redis version: `4.0.9`
* Python version: `3.6.9`

## Problem Description
I am attempting to run `bootstrap`, and am running into an odd issue where **psycopg2** is raising a `psycopg2.errors.SyntaxError` for the statement `FROM (VALUES ) AS v (table_name, foreign_keys)`.

My `schema.json` file seems to be quite simple, so I'm skeptical that it is the issue. It resembles the following:
```json
[
  {
    "database": "my_database",
    "index": "my_database",
    "nodes": {
      "table": "flags_featureconfig"
    }
  }
]
```

## Error Message (if any)
Console logs as a result of running `bootstrap --config schema.json -v`.
```
pg_settings:
SELECT setting
FROM pg_settings
WHERE name = %(name_1)spg_settings:
SELECT setting
FROM pg_settings
WHERE name = %(name_1)spg_settings:
SELECT setting
FROM pg_settings
WHERE name = %(name_1)shas_permission:
SELECT usesuper
FROM pg_user
WHERE usename = %(usename_1)s
  AND usesuper = TRUE/home/vagrant/.local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3811: SAWarning: Did not recognize type 'geometry' of column 'extent'
  "Did not recognize type '%s' of column '%s'" % (attype, name)
 - flags_featureconfig
replication_slots:
SELECT *
FROM PG_REPLICATION_SLOTS
WHERE slot_name = %(slot_name_1)s
  AND slot_type = %(slot_type_1)s
  AND plugin = %(plugin_1)sSELECT table_constraints_1.table_name,
       array_agg(CAST(key_column_usage_1.column_name AS TEXT)) AS foreign_keys
FROM information_schema.table_constraints AS table_constraints_1
JOIN information_schema.key_column_usage AS key_column_usage_1 ON key_column_usage_1.constraint_name = table_constraints_1.constraint_name
AND key_column_usage_1.table_schema = table_constraints_1.table_schema
JOIN information_schema.constraint_column_usage AS constraint_column_usage_1 ON constraint_column_usage_1.constraint_name = table_constraints_1.constraint_name
AND constraint_column_usage_1.table_schema = table_constraints_1.table_schema
WHERE table_constraints_1.table_name IN ([POSTCOMPILE_table_name_1])
  AND table_constraints_1.constraint_type = %(constraint_type_1)s
GROUP BY table_constraints_1.table_nameTraceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1707, in _execute_context
    cursor, statement, parameters, context
  File "/home/vagrant/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 2: FROM (VALUES ) AS v (table_name, foreign_keys)
                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/.local/bin/bootstrap", line 68, in <module>
    main()
  File "/home/vagrant/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.local/bin/bootstrap", line 63, in main
    sync.setup()
  File "/home/vagrant/.local/lib/python3.6/site-packages/pgsync/sync.py", line 191, in setup
    self.create_views(schema, tables, user_defined_fkey_tables)
  File "/home/vagrant/.local/lib/python3.6/site-packages/pgsync/base.py", line 620, in create_views
    statement,
  File "<string>", line 2, in execute
  File "/home/vagrant/.local/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/home/vagrant/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 3038, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/vagrant/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1201, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/vagrant/.local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 78, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/vagrant/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1297, in _execute_ddl
    compiled,
  File "/home/vagrant/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1750, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/vagrant/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1931, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/vagrant/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/vagrant/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1707, in _execute_context
    cursor, statement, parameters, context
  File "/home/vagrant/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near ")"
LINE 2: FROM (VALUES ) AS v (table_name, foreign_keys)
                     ^

[SQL: CREATE MATERIALIZED VIEW "public"."_fkey_view" AS SELECT v.table_name, v.foreign_keys
FROM (VALUES ) AS v (table_name, foreign_keys)]
(Background on this error at: http://sqlalche.me/e/14/f405)
```

**Comment by toluaina** [comment]
This has been fixed in master. Sorry about that

**Comment by toluaina** [comment]
Thanks!

**Comment by rafaelvascc** [comment]
``@toluaina 
I'm having the same issue trying to to run pgsync on a docker Ubuntu container installing it with pip.

Here is the content of my Dockerfile:

FROM ubuntu:20.04
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-get update
RUN add-apt-repository universe
RUN apt-get update
RUN apt install -y python3
RUN apt install -y python3-pip
RUN yes | pip install pgsync
ENV PG_USER=postgres
ENV PG_HOST=host.docker.internal
ENV PG_PORT=5432
ENV PG_PASSWORD=mysecretpassword
ENV LOG_LEVEL=INFO
ENV ELASTICSEARCH_PORT=9200
ENV ELASTICSEARCH_SCHEME=http
ENV ELASTICSEARCH_HOST=host.docker.internal
ENV REDIS_HOST=host.docker.internal
ADD schema.json /
RUN bootstrap --config /schema.json
CMD [ "pgsync", "--config", "/schema.json", "--daemon" ]

And here is my schema.json

[
    {
        "database": "oneordersintegration",
        "index": "orders",
        "nodes": {
            "table": "Orders",
            "schema": "public",
            "columns": [
                "Id",
                "CreatedAt",
                "LastModifiedAt",
                "CreatedBy",
                "CreatedBy",
                "LastModifiedBy",
                "Version"
            ]
        }
    }
]

Is there any prediction on when this fix will be available for the "pip installation"?

Thanks.
