### ISSUE TITLE
Superuser issue on Amazon RDS / Aurora ?

### ISSUE THREAD

**Issue by meetri** [toluaina/pgsync#125]
PGSync version: 
1.0.1 - 2.0.0

Postgres version: 

Elasticsearch version: 

Redis version: 

Python version: 

Problem Description: 
has this tool been tested or designed to work on aws rds postgres instances.
they lock down superuser access so, i'm not sure if this tool will work.

thank you

Error Message (if any): 

```
Traceback (most recent call last):
  File "/usr/local/bin/pgsync", line 7, in <module>
    sync.main()
  File "pgsync/utils.py", line 82, in pgsync.utils.timeit.timed
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "pgsync/sync.py", line 769, in pgsync.sync.main
  File "pgsync/sync.py", line 59, in pgsync.sync.Sync.__init__
  File "pgsync/sync.py", line 67, in pgsync.sync.Sync.validate
pgsync.exc.SuperUserError: 'You need to be a superuser to perform this action: Current user: user1'

```

**Comment by toluaina** [comment]
Yea, you need to enable replication slots as described in the [docs](https://pgsync.com/getting-started/setup/)
