### ISSUE TITLE
error: Table not specified in node: {}

### ISSUE THREAD

**Issue by kz-fincert** [toluaina/pgsync#128]
PGSync version: last

Postgres version: 13.3

Elasticsearch version: 7.11.2

Python version: 3.9.5

Problem Description: 
when initializing bootstrap --config schema.json getting an error

Error Message (if any): 

```
Traceback (most recent call last):
  File "/usr/local/bin/bootstrap", line 68, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/bootstrap", line 59, in main
    sync = Sync(document, verbose=verbose, repl_slots=False, **params)
  File "/usr/local/lib/python3.9/site-packages/pgsync/sync.py", line 84, in __init__
    self.validate(repl_slots=repl_slots)
  File "/usr/local/lib/python3.9/site-packages/pgsync/sync.py", line 150, in validate
    root = self.tree.build(self.nodes)
  File "/usr/local/lib/python3.9/site-packages/pgsync/node.py", line 250, in build
    raise TableNotInNodeError(
pgsync.exc.TableNotInNodeError: 'Table not specified in node: {}'
Traceback (most recent call last):
  File "/usr/local/bin/bootstrap", line 68, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/bootstrap", line 59, in main
    sync = Sync(document, verbose=verbose, repl_slots=False, **params)
  File "/usr/local/lib/python3.9/site-packages/pgsync/sync.py", line 84, in __init__
    self.validate(repl_slots=repl_slots)
  File "/usr/local/lib/python3.9/site-packages/pgsync/sync.py", line 150, in validate
    root = self.tree.build(self.nodes)
  File "/usr/local/lib/python3.9/site-packages/pgsync/node.py", line 250, in build
    raise TableNotInNodeError(
pgsync.exc.TableNotInNodeError: 'Table not specified in node: {}'

```
schema.json:
```
[
  {
    "database": "irp_database",
    "index": "irp-data-signal",
    "node": {
      "table": "irp_signal",
      "schema": "public",
      "columns": [
        "created_at",
        "updated_at",
        "closed_at"
      ]
    }
  }
]
```

**Comment by kz-fincert** [comment]
The question is removed, it was necessary to specify node**s** and not node
