### ISSUE TITLE
Unable to use plugin - ModuleNotFoundError: No module named 'plugins'

### ISSUE THREAD

**Issue by ejekanshjain** [toluaina/pgsync#155]
PGSync version: 2.1.1

Postgres version: 13.4

Elasticsearch version: 7.14.0

Redis version: 6.2.5

Python version: 3.9.5

Problem Description: I have created a schema.json file and plugins/customplugin.py file as mentioned in docs to sync products table into elastic search. But I get the below error whenever I try to sync it. I use this command for running the sync
```
pgsync --config ./schema.json
```

Error Message (if any): 

```
0:00:00.011480 (0.01 sec)
Traceback (most recent call last):
  File "/home/ekansh/DME_PXM/util/PGSYNC/venv/bin/pgsync", line 7, in <module>
    sync.main()
  File "/home/ekansh/DME_PXM/util/PGSYNC/venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/ekansh/DME_PXM/util/PGSYNC/venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/ekansh/DME_PXM/util/PGSYNC/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ekansh/DME_PXM/util/PGSYNC/venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/ekansh/DME_PXM/util/PGSYNC/venv/lib/python3.9/site-packages/pgsync/sync.py", line 1088, in main
    sync = Sync(
  File "/home/ekansh/DME_PXM/util/PGSYNC/venv/lib/python3.9/site-packages/pgsync/sync.py", line 82, in __init__
    self.validate(repl_slots=repl_slots)
  File "/home/ekansh/DME_PXM/util/PGSYNC/venv/lib/python3.9/site-packages/pgsync/sync.py", line 97, in validate
    self._plugins = Plugins("plugins", self.plugins)
  File "/home/ekansh/DME_PXM/util/PGSYNC/venv/lib/python3.9/site-packages/pgsync/plugin.py", line 25, in __init__
    self.reload()
  File "/home/ekansh/DME_PXM/util/PGSYNC/venv/lib/python3.9/site-packages/pgsync/plugin.py", line 32, in reload
    self.walk(self.package)
  File "/home/ekansh/DME_PXM/util/PGSYNC/venv/lib/python3.9/site-packages/pgsync/plugin.py", line 36, in walk
    plugins = importlib.import_module(package)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins'
```

Here's my files I have in my project

schema.json
```
[
  {
    "database": "mes-pxm-prod",
    "index": "products-search",
    "plugins": ["Custom"],
    "nodes": {
      "table": "Products",
      "schema": "public",
      "columns": ["id", "name", "sku", "createdAt", "updatedAt"]
    }
  }
]
```

plugins/customplugin.py
```
from pgsync import plugin

class CustomPlugin(plugin.Plugin):
    name = 'Custom'
    def transform(self, doc, **kwargs):
        doc['custom'] = 'custom'
        return doc
```

**Comment by toluaina** [comment]
You need to make sure that the path to `customplugin.py` is in your **PYTHONPATH**

**Comment by ejekanshjain** [comment]
![Screenshot from 2021-08-17 11-48-35](https://user-images.githubusercontent.com/33418543/129673789-761cd9c3-0628-4cf6-8c2b-9c099f0b6439.png)

Still getting same error after adding PYTHONPATH in .bashrc

**Comment by toluaina** [comment]
Sorry about this. you should have a `plugins` directory. And the path to this `plugins` should be in your `PYTHONPATH`

**Comment by ejekanshjain** [comment]
Yes, but still don't know why I am getting error

**Comment by toluaina** [comment]
From the screenshot above, this path should be in your PYTHONPATH.
`/home/ekansh/DME_PXM/util/PGSYNC `

and you should also add an empty `__init__.py` in the plugins directory

**Comment by ejekanshjain** [comment]
It Worked. Thanks.
