### ISSUE TITLE
pgsync同步父子关系报错psycopg2.errors.UniqueViolation: could not create unique index "fkey_idx"  DETAIL: Key (table_name)=(comment) is duplicated.

### ISSUE THREAD

**Issue by 635503281** [toluaina/pgsync#156]
PGSync version: latest

Postgres version: 13.2

Elasticsearch version: 7.6

Redis version: 6.2.2

Python version: 3.7.10

Problem Description: 

配置父子关联关系像这样就报错
![image](https://user-images.githubusercontent.com/33439639/129649889-07b65217-b6d2-4e53-aaf4-0fa08f6bc278.png)

Error Message (if any): 
Traceback (most recent call last):

File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context

cursor, statement, parameters, context

File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute

cursor.execute(statement, parameters)

psycopg2.errors.UniqueViolation: could not create unique index "fkey_idx"

DETAIL: Key (table_name)=(comment) is duplicated.

**Comment by 635503281** [comment]
问题描述中的PGSync version应该不是最新版本的，我现在用最新重新打了个镜像运行，报错：
"Incompatible schema. Please run v2 schema migration"
