### ISSUE TITLE
Error during sync and stop of sync after error

### ISSUE THREAD

**Issue by kostyatimo** [toluaina/pgsync#169]
PGSync version: 
2.1.1 and https://github.com/toluaina/pgsync/archive/refs/heads/master.zip
Postgres version: 
postgres:12

Elasticsearch version: 
7.14.0

Python version: 
3.7.11

Problem Description: 
I've setup docker-compose with database, elastic, redis and pgsync.
Then I've run tests, which run one by one, but they are making bunch of changes in database. 
I see that sync is slow and sometimes I see error, after error it stops sync. In log I can see only
```
Polling db testing: 456 item(s)
Polling db testing: 456 item(s)
Polling db testing: 463 item(s)
Polling db testing: 463 item(s)
Polling db testing: 463 item(s)
```
I've tried different settings. One of set:
      - ELASTICSEARCH_THREAD_COUNT=1
      - ELASTICSEARCH_QUEUE_SIZE=1
      - ELASTICSEARCH_STREAMING_BULK=True
      - ELASTICSEARCH_MAX_RETRIES=5
      - ELASTICSEARCH_INITIAL_BACKOFF=5
      

Error Message (if any): 
`Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 888, in poll_redis
    self.on_publish(payloads)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 969, in on_publish
    self.sync(self._payloads(_payloads))
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 860, in sync
    self.es.bulk(self.index, docs)
  File "/usr/local/lib/python3.7/site-packages/pgsync/elastichelper.py", line 104, in bulk
    refresh=refresh,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 320, in streaming_bulk
    actions, chunk_size, max_chunk_bytes, client.transport.serializer
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
    for action, data in actions:
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 692, in _payloads
    payloads,
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 535, in _delete
    self.es.bulk(self.index, docs)
  File "/usr/local/lib/python3.7/site-packages/pgsync/elastichelper.py", line 104, in bulk
    refresh=refresh,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 339, in streaming_bulk
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 256, in _process_bulk_chunk
    for item in gen:
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 187, in _process_bulk_chunk_success
    raise BulkIndexError("%i document(s) failed to index." % len(errors), errors)
elasticsearch.helpers.errors.BulkIndexError: ('9 document(s) failed to index.', [{'delete': {'_index': 'orders_list_response', '_type': '_doc', '_id': '1916', '_version': 1, 'result': 'not_found', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 255341, '_primary_term': 3, 'status': 404}}, {'delete': {'_index': 'orders_list_response', '_type': '_doc', '_id': '1916', '_version': 2, 'result': 'not_found', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 255342, '_primary_term': 3, 'status': 404}}, {'delete': {'_index': 'orders_list_response', '_type': '_doc', '_id': '1916', '_version': 3, 'result': 'not_found', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 255343, '_primary_term': 3, 'status': 404}}, {'delete': {'_index': 'orders_list_response', '_type': '_doc', '_id': '1917', '_version': 1, 'result': 'not_found', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 255344, '_primary_term': 3, 'status': 404}}, {'delete': {'_index': 'orders_list_response', '_type': '_doc', '_id': '1917', '_version': 2, 'result': 'not_found', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 255345, '_primary_term': 3, 'status': 404}}, {'delete': {'_index': 'orders_list_response', '_type': '_doc', '_id': '1917', '_version': 3, 'result': 'not_found', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 255346, '_primary_term': 3, 'status': 404}}, {'delete': {'_index': 'orders_list_response', '_type': '_doc', '_id': '1918', '_version': 1, 'result': 'not_found', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 255347, '_primary_term': 3, 'status': 404}}, {'delete': {'_index': 'orders_list_response', '_type': '_doc', '_id': '1918', '_version': 2, 'result': 'not_found', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 255348, '_primary_term': 3, 'status': 404}}, {'delete': {'_index': 'orders_list_response', '_type': '_doc', '_id': '1918', '_version': 3, 'result': 'not_found', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 255349, '_primary_term': 3, 'status': 404}}])

`

**Comment by kostyatimo** [comment]
Yes, all time during running tests. When run a lot of requests at  short period of time. There are create, update, delete changes.
I've tested on small database from 10-2000 items. I've tested with default options also.
Config contains schema with about 50 fields of main object and about 5 nested objects with 2-10 fields inside.
Is it possible to have logical issue with bulk updates of elastic if do create, update and delete quickly?

**Comment by toluaina** [comment]
Can you possibly share your testing strategy?
Can this be applied to one of the existing examples?

**Comment by kostyatimo** [comment]
Tests check different test cases in system.
yes, such error happened during it, if run only one query to db it works fine.

**Comment by jadsy2107** [comment]
Having the same issue: 
![Screen Shot 2022-12-04 at 3 01 36 pm](https://user-images.githubusercontent.com/107200645/205473707-ac6249af-5b4f-4f18-870d-245bb17c39ae.png)
