### ISSUE TITLE
Build 2.1.4 is throwing an exception.

### ISSUE THREAD

**Issue by voyc-jean** [toluaina/pgsync#183]
PGSync version:  2.1.4
Python version: 3.8.10

Problem Description: 
Since version 2.1.4 an exception is thrown on startup due to a missing import.

Error Message (if any): 

```
Traceback (most recent call last):
File "/usr/local/bin/pgsync", line 4, in <module>
from pgsync import sync
File "/usr/local/lib/python3.8/site-packages/pgsync/sync.py", line 22, in <module>
from .base import Base, compiled_query, get_foreign_keys
File "/usr/local/lib/python3.8/site-packages/pgsync/base.py", line 931, in <module>
def get_foreign_keys(node_a: Node, node_b: Node) -> dict:
NameError: name 'Node' is not defined
Traceback (most recent call last):
File "/usr/local/bin/bootstrap", line 9, in <module>
from pgsync.sync import Sync
File "/usr/local/lib/python3.8/site-packages/pgsync/sync.py", line 22, in <module>
from .base import Base, compiled_query, get_foreign_keys
File "/usr/local/lib/python3.8/site-packages/pgsync/base.py", line 931, in <module>
def get_foreign_keys(node_a: Node, node_b: Node) -> dict:
NameError: name 'Node' is not defined
```

**Comment by toluaina** [comment]
Yes sorry about that. I noticed, fixed and published a new version
