### ISSUE TITLE
Trying to redefine primary-key column 'oid' as a non-primary-key column on table 'pg_catalog.pg_class'

### ISSUE THREAD

**Issue by RaduGabor** [toluaina/pgsync#195]
PGSync version:  2.1.6

Postgres version: 14

Elasticsearch version: 7.13.2

Redis version: 6.2.4

Python version:  3.7.12

Problem Description: 

When running bootstrap command I get an error.

Error Message (if any): 

```
root@821ef5a6f893:/code# bootstrap --config pgsync.json
2021-10-14 13:23:50.384:WARNING:pgsync.utils: ModuleNotFoundError: No module named 'plugins'
2021-10-14 13:23:50.387:WARNING:pgsync.utils: ModuleNotFoundError: No module named 'plugins'
2021-10-14 13:23:50.390:WARNING:pgsync.utils: ModuleNotFoundError: No module named 'plugins'
/usr/local/lib/python3.7/site-packages/pgsync/base.py:123: SAWarning: Did not recognize type 'point' of column 'coordinates'
  metadata.reflect(self.__engine, views=True)
 - worker_profiles
   |- users
   |- worker_interests
   |- worker_locations
   |- worker_incomes
   |- worker_hard_skills
   |  |- hard_skills
   |   - domains
   |- worker_soft_skills
   |   - soft_skills
    - worker_schedule
Traceback (most recent call last):
  File "/usr/local/bin/bootstrap", line 66, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/bin/bootstrap", line 61, in main
    sync.setup()
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 216, in setup
    self.create_view(schema, tables, user_defined_fkey_tables)
  File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 547, in create_view
    self._primary_keys(schema, tables)
  File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 373, in _primary_keys
    pg_class = self.model("pg_class", "pg_catalog")
  File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 132, in model
    model.append_column(sa.Column("oid", sa.dialects.postgresql.OID))
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 891, in append_column
    self, allow_replacements=replace_existing
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 1029, in _set_parent_with_dispatch
    self._set_parent(parent, **kw)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 1798, in _set_parent
    % (self.key, table.fullname)
sqlalchemy.exc.ArgumentError: Trying to redefine primary-key column 'oid' as a non-primary-key column on table 'pg_catalog.pg_class'

```

**Comment by RaduGabor** [comment]
I've downgraded to Postgres 13 and it works.

**Comment by toluaina** [comment]
closing this issue

**Comment by mohanagy** [comment]
not fixed

**Comment by toluaina** [comment]
@mohanagy 

Would you mind opening a new issue with some details include any stacktrace please.
