### ISSUE TITLE
TRUNCATE statement is not propagated correctly to Elasticsearch whereas INSERT, UPDATE and DELETE works fine!

### ISSUE THREAD

**Issue by enterpinamullah** [toluaina/pgsync#197]
PGSync version: 2.1.7

Postgres version: 13

Elasticsearch version: 7.14.2 

Redis version: 2.4.6

Python version: 3.9

Problem Description: 
Truncate Statement is not propagated correctly to elasticsearch and error given below is thrown!

Error Message (if any): 

```
2021-10-21 16:45:13.012:ERROR:pgsync.sync: Exception 'bool' object is not callable
Traceback (most recent call last):
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\sync.py", line 884, in sync
    self.es.bulk(self.index, docs)
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\elastichelper.py", line 111, in bulk
    for _ in helpers.parallel_bulk(
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\site-packages\elasticsearch\helpers\actions.py", line 472, in parallel_bulk
    for result in pool.imap(
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 870, in next
    raise value
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\site-packages\elasticsearch\helpers\actions.py", line 155, in _chunk_actions
    for action, data in actions:
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\sync.py", line 714, in _payloads
    filters = self._truncate(node, root, filters)
TypeError: 'bool' object is not callable
Exception in thread Thread-16:
Traceback (most recent call last):
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\sync.py", line 913, in poll_redis
    self.on_publish(payloads)
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\sync.py", line 1001, in on_publish
    self.sync(self._payloads(_payloads))
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\sync.py", line 884, in sync
    self.es.bulk(self.index, docs)
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\elastichelper.py", line 111, in bulk
    for _ in helpers.parallel_bulk(
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\site-packages\elasticsearch\helpers\actions.py", line 472, in parallel_bulk
    for result in pool.imap(
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 870, in next
    raise value
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\site-packages\elasticsearch\helpers\actions.py", line 155, in _chunk_actions
    for action, data in actions:
  File "C:\Users\Inam\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\sync.py", line 714, in _payloads
    filters = self._truncate(node, root, filters)

```

**Comment by toluaina** [comment]
Do you have a high constant write rate to your db?
I would suggest doing a benchmark to see how this works in prod.
Maybe you can use [this](https://github.com/toluaina/pgsync/blob/master/examples/book/benchmark.py) as a starting point to simulate the db writes
You might also want to measure the writes per second with and without the triggers.
