### ISSUE TITLE
Checks for Major version 7 fail for OpenSearch

### ISSUE THREAD

**Issue by JacobReynolds** [toluaina/pgsync#207]
PGSync version: 
2.1.9

Postgres version: 
12

Elasticsearch version: 
Opensearch 1.1.0

Redis version: 
6.2.6

Python version: 
3.7

Problem Description: 
When using Opensearch, checks for ElasticSearch v7 fail, due to OpenSearch starting at major version 1. This causes things like the node -> transform -> mapping schema option to fail.

https://github.com/toluaina/pgsync/blob/master/pgsync/elastichelper.py#L259

Error Message (if any): 

```
pgsync_1      | 2021-11-16 21:19:09.993:WARNING:elasticsearch: PUT http://opensearch:9200/domain [status:400 request:0.003s]
pgsync_1      | Traceback (most recent call last):
pgsync_1      |   File "/usr/local/bin/pgsync", line 7, in <module>
pgsync_1      |     sync.main()
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
pgsync_1      |     return self.main(*args, **kwargs)
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1053, in main
pgsync_1      |     rv = self.invoke(ctx)
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
pgsync_1      |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
pgsync_1      |     return __callback(*args, **kwargs)
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 1138, in main
pgsync_1      |     sync = Sync(document, verbose=verbose, **kwargs)
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 99, in __init__
pgsync_1      |     self.create_setting()
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 185, in create_setting
pgsync_1      |     routing=self.routing,
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/pgsync/elastichelper.py", line 201, in _create_setting
pgsync_1      |     body=body,
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
pgsync_1      |     return func(*args, params=params, headers=headers, **kwargs)
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 124, in create
pgsync_1      |     "PUT", _make_path(index), params=params, headers=headers, body=body
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 415, in perform_request
pgsync_1      |     raise e
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 388, in perform_request
pgsync_1      |     timeout=timeout,
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 277, in perform_request
pgsync_1      |     self._raise_error(response.status, raw_data)
pgsync_1      |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 331, in _raise_error
pgsync_1      |     status_code, error_message, additional_info
pgsync_1      | elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true.')

```

**Comment by toluaina** [comment]
I have addressed this in master. Can you give it a try and let me know

**Comment by JacobReynolds** [comment]
That looks great, thank you!
