### ISSUE TITLE
PGSync SQLAlchemy errors when trying to sync a column "items" with type integer, but works with other integer columns

### ISSUE THREAD

**Issue by rjdlee** [toluaina/pgsync#232]
Operating System: Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-96-generic x86_64)

PGSync version: 2.1.10

Postgres version: 13.5

Elasticsearch version: 7.16.3

Redis version: 5.0.7

Python version: Python 3.8.10

Problem Description: 

PGSync SQLAlchemy errors when trying to sync a column called "items" with SQL type integer, but it works with another integer column called "owners". The error appears during syncing, not during bootstrap.

My SQL schema looks like:
```
name: text (Primary Key)
policy_id: text (Unique)
items: integer
owners: integer
```

My schema.json:
```
[
  {
    "index": "test_index",
    "setting": {
      ... // Omitted for brevity
   },
    "nodes": {
      "table": "collections",
      "schema": "public",
      "columns": [
        "policy_id",
        "name",
        "owners", // Owners column works
        "items" // Items column fails with the error below
      ],
      "transform": {
        "mapping":  {
            "name": {
               "type": "text",
               "analyzer": "custom_edge_ngram_analyzer"
              }
          }
        }
      }
    }
]
```

Error Message (if any): 

```
 2022-01-22 21:00:33.169:ERROR:pgsync.elastichelper: Exception (psycopg2.ProgrammingError) can't adapt type 'method'
 [SQL: SELECT anon_1."JSON_BUILD_ARRAY_1", anon_1."JSON_BUILD_OBJECT_1", anon_1.name
 FROM (SELECT JSON_BUILD_ARRAY() AS "JSON_BUILD_ARRAY_1", JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_2)s, collections_1.policy_id, %(JSON_BUILD_OBJECT_3)s, collections_1.name, %(JSON_BUILD_OBJECT_4)s, collections_1.display_name, %(JSON_BUILD_OBJECT_5)s, collections_1.hero_image_file_type, %(JSON_BUILD_OBJECT_6)s, collections_1.owners, %(JSON_BUILD_OBJECT_7)s, %(JSON_BUILD_OBJECT_8)s) AS "JSON_BUILD_OBJECT_1", collections_1.name AS name
 FROM public.collections AS collections_1
 WHERE CAST(CAST(collections_1.xmin AS TEXT) AS BIGINT) < %(param_1)s) AS anon_1]
 [parameters: {'JSON_BUILD_OBJECT_2': 'policy_id', 'JSON_BUILD_OBJECT_3': 'name', 'JSON_BUILD_OBJECT_4': 'display_name', 'JSON_BUILD_OBJECT_5': 'hero_image_file_type', 'JSON_BUILD_OBJECT_6': 'owners', 'JSON_BUILD_OBJECT_7': 'items', 'JSON_BUILD_OBJECT_8': <bound method ColumnCollection.items of <sqlalchemy.sql.base.ImmutableColumnCollection object at 0x7f36c68dbf90>>, 'param_1': 8753184}]
 (Background on this error at: https://sqlalche.me/e/14/f405)
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
     self.dialect.do_execute(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
     cursor.execute(statement, parameters)
 psycopg2.ProgrammingError: can't adapt type 'method'
 The above exception was the direct cause of the following exception:
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/dist-packages/pgsync/elastichelper.py", line 106, in bulk
     self._bulk(
   File "/usr/local/lib/python3.8/dist-packages/pgsync/elastichelper.py", line 172, in _bulk
     for _ in helpers.parallel_bulk(
   File "/usr/local/lib/python3.8/dist-packages/elasticsearch/helpers/actions.py", line 472, in parallel_bulk
     for result in pool.imap(
   File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
     raise value
   File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
     result = (True, func(*args, **kwds))
   File "/usr/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
     raise ex
   File "/usr/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
     for i, x in enumerate(iterable):
   File "/usr/local/lib/python3.8/dist-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
     for action, data in actions:
   File "/usr/local/lib/python3.8/dist-packages/pgsync/sync.py", line 823, in sync
     for i, (keys, row, primary_keys) in enumerate(
   File "/usr/local/lib/python3.8/dist-packages/pgsync/base.py", line 783, in fetchmany
     result = conn.execution_options(stream_results=True).execute(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1289, in execute
     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
     return connection._execute_clauseelement(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
     ret = self._execute_context(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
     self._handle_dbapi_exception(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
     util.raise_(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
     raise exception
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
     self.dialect.do_execute(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
     cursor.execute(statement, parameters)
 sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'method'
 [SQL: SELECT anon_1."JSON_BUILD_ARRAY_1", anon_1."JSON_BUILD_OBJECT_1", anon_1.name
 FROM (SELECT JSON_BUILD_ARRAY() AS "JSON_BUILD_ARRAY_1", JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_2)s, collections_1.policy_id, %(JSON_BUILD_OBJECT_3)s, collections_1.name, %(JSON_BUILD_OBJECT_4)s, collections_1.display_name, %(JSON_BUILD_OBJECT_5)s, collections_1.hero_image_file_type, %(JSON_BUILD_OBJECT_6)s, collections_1.owners, %(JSON_BUILD_OBJECT_7)s, %(JSON_BUILD_OBJECT_8)s) AS "JSON_BUILD_OBJECT_1", collections_1.name AS name
 FROM public.collections AS collections_1
 WHERE CAST(CAST(collections_1.xmin AS TEXT) AS BIGINT) < %(param_1)s) AS anon_1]
 [parameters: {'JSON_BUILD_OBJECT_2': 'policy_id', 'JSON_BUILD_OBJECT_3': 'name', 'JSON_BUILD_OBJECT_4': 'display_name', 'JSON_BUILD_OBJECT_5': 'hero_image_file_type', 'JSON_BUILD_OBJECT_6': 'owners', 'JSON_BUILD_OBJECT_7': 'items', 'JSON_BUILD_OBJECT_8': <bound method ColumnCollection.items of <sqlalchemy.sql.base.ImmutableColumnCollection object at 0x7f36c68dbf90>>, 'param_1': 8753184}]
 (Background on this error at: https://sqlalche.me/e/14/f405)
  0:00:38.467140 (38.47 sec)
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
     self.dialect.do_execute(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
     cursor.execute(statement, parameters)
 psycopg2.ProgrammingError: can't adapt type 'method'
 The above exception was the direct cause of the following exception:
 Traceback (most recent call last):
   File "/usr/local/bin/pgsync", line 7, in <module>
     sync.main()
   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
     return self.main(*args, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
     rv = self.invoke(ctx)
   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
     return ctx.invoke(self.callback, **ctx.params)
   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
     return __callback(*args, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/pgsync/sync.py", line 1125, in main
     sync.pull()
   File "/usr/local/lib/python3.8/dist-packages/pgsync/sync.py", line 975, in pull
     self.es.bulk(self.index, self.sync(txmin=txmin, txmax=txmax))
   File "/usr/local/lib/python3.8/dist-packages/pgsync/elastichelper.py", line 106, in bulk
     self._bulk(
   File "/usr/local/lib/python3.8/dist-packages/pgsync/elastichelper.py", line 172, in _bulk
     for _ in helpers.parallel_bulk(
   File "/usr/local/lib/python3.8/dist-packages/elasticsearch/helpers/actions.py", line 472, in parallel_bulk
     for result in pool.imap(
   File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
     raise value
   File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
     result = (True, func(*args, **kwds))
   File "/usr/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
     raise ex
   File "/usr/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
     for i, x in enumerate(iterable):
   File "/usr/local/lib/python3.8/dist-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
     for action, data in actions:
   File "/usr/local/lib/python3.8/dist-packages/pgsync/sync.py", line 823, in sync
     for i, (keys, row, primary_keys) in enumerate(
   File "/usr/local/lib/python3.8/dist-packages/pgsync/base.py", line 783, in fetchmany
     result = conn.execution_options(stream_results=True).execute(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1289, in execute
     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
     return connection._execute_clauseelement(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
     ret = self._execute_context(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
     self._handle_dbapi_exception(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
     util.raise_(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
     raise exception
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
     self.dialect.do_execute(
   File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
     cursor.execute(statement, parameters)
 sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'method'
 [SQL: SELECT anon_1."JSON_BUILD_ARRAY_1", anon_1."JSON_BUILD_OBJECT_1", anon_1.name
 FROM (SELECT JSON_BUILD_ARRAY() AS "JSON_BUILD_ARRAY_1", JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_2)s, collections_1.policy_id, %(JSON_BUILD_OBJECT_3)s, collections_1.name, %(JSON_BUILD_OBJECT_4)s, collections_1.display_name, %(JSON_BUILD_OBJECT_5)s, collections_1.hero_image_file_type, %(JSON_BUILD_OBJECT_6)s, collections_1.owners, %(JSON_BUILD_OBJECT_7)s, %(JSON_BUILD_OBJECT_8)s) AS "JSON_BUILD_OBJECT_1", collections_1.name AS name
 FROM public.collections AS collections_1
 WHERE CAST(CAST(collections_1.xmin AS TEXT) AS BIGINT) < %(param_1)s) AS anon_1]
 [parameters: {'JSON_BUILD_OBJECT_2': 'policy_id', 'JSON_BUILD_OBJECT_3': 'name', 'JSON_BUILD_OBJECT_4': 'display_name', 'JSON_BUILD_OBJECT_5': 'hero_image_file_type', 'JSON_BUILD_OBJECT_6': 'owners', 'JSON_BUILD_OBJECT_7': 'items', 'JSON_BUILD_OBJECT_8': <bound method ColumnCollection.items of <sqlalchemy.sql.base.ImmutableColumnCollection object at 0x7f36c68dbf90>>, 'param_1': 8753184}]
 (Background on this error at: https://sqlalche.me/e/14/f405)
```

**Comment by toluaina** [comment]
Thanks for this report. This has been fixed in the master branch.

**Comment by rjdlee** [comment]
Thank you!
