### ISSUE TITLE
issues with " Multiple schemas in single config"

### ISSUE THREAD

**Issue by ensbergbis** [toluaina/pgsync#236]
PGSync version:  psycopg2                  2.7.7 

Postgres version: 13

Elasticsearch version: 7.13.4

Python version: 3.8

Problem Description:  

Hello;
Please I have two independnate sql tables and I would like to sync them with two indexes
I followed the following instruction
[](https://pgsync.com/tutorial/multiple-schemas-in-single-config/)

but i get error message : pgsync.exc.TableNotFoundError: 'Table "public.siv_Final" not found in registry'

this is what i have in my sql file 
` CREATE TABLE  siv_Final  (id_technique  bigint,  c_marque TEXT, c_nation_comm varchar(30) ,  PRIMARY KEY ("id_technique"));

CREATE TABLE  Mouvements  (id_technique  bigint,  f_ma TEXT, w_deno_comm varchar(30) , b4_num_plaque varchar(30) , operation  INTEGER , PRIMARY KEY ("id_technique"));`

this is my Json schema 

`[
  {
    "database": "postgres",
    "index": "siv_Final_index",
    "nodes": {
      "table": "siv_Final"
    }
  }
  ,

  {
    "database": "postgres",
    "index": "Mouvements_index",
    "nodes": {
      "table": "Mouvements"
      

    }
  }

`
i try with and without add a columns but i hava the same error

Error Message (if any): issues with " Multiple schemas in single config"

Traceback (most recent call last):
pgsync_init_M    |   File "/usr/local/bin/bootstrap", line 66, in <module>
pgsync_init_M    |     main()
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
pgsync_init_M    |     return self.main(*args, **kwargs)
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1062, in main
pgsync_init_M    |     rv = self.invoke(ctx)
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
pgsync_init_M    |     return ctx.invoke(self.callback, **ctx.params)
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
pgsync_init_M    |     return __callback(*args, **kwargs)
pgsync_init_M    |   File "/usr/local/bin/bootstrap", line 57, in main
pgsync_init_M    |     sync = Sync(document, verbose=verbose, repl_slots=False, **params)
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 82, in __init__
pgsync_init_M    |     self.validate(repl_slots=repl_slots)
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 149, in validate
pgsync_init_M    |     root = self.tree.build(self.nodes)
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/pgsync/node.py", line 255, in build
pgsync_init_M    |     model=self.base.model(table, schema=schema),
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 133, in model
pgsync_init_M    |     f'Table "{name}" not found in registry'
pgsync_init_M    | pgsync.exc.TableNotFoundError: 'Table "public.siv_Final" not found in registry'
pgsync_init_M    |  0:00:00.022372 (0.02 sec)
pgsync_init_M    | Traceback (most recent call last):
pgsync_init_M    |   File "/usr/local/bin/pgsync", line 7, in <module>
pgsync_init_M    |     sync.main()
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
pgsync_init_M    |     return self.main(*args, **kwargs)
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1062, in main
pgsync_init_M    |     rv = self.invoke(ctx)
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
pgsync_init_M    |     return ctx.invoke(self.callback, **ctx.params)
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
pgsync_init_M    |     return __callback(*args, **kwargs)
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 1091, in main
pgsync_init_M    |     params=params,
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 82, in __init__
pgsync_init_M    |     self.validate(repl_slots=repl_slots)
pgsync_init_M    |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 145, in validate
pgsync_init_M    |     f'Replication slot "{self.__name}" does not exist.\n'
pgsync_init_M    | RuntimeError: Replication slot "postgres_siv_Final_index" does not exist.
pgsync_init_M    | Make sure you have run "bootstrap".

```


```

**Comment by toluaina** [comment]
- Did you run the bootstrap command?
- Also it might be advisable to use lower case names
