### ISSUE TITLE
Error: while pushing data to elastic

### ISSUE THREAD

**Issue by Eklavaya** [toluaina/pgsync#244]
PGSync version: latest (installed from PIP)

Postgres version: 14.1

Elasticsearch version: 6.8.6

Redis version: 5.0.8

Python version: 3.7

Problem Description: 
bootstrap pushed a lot of entries to elastic but then throw below error. is it possible it is due to 1 million entries?

Error Message (if any): 

```
2022-02-09 10:05:44.896:INFO:elasticsearch: POST http://<url>:9200/_bulk?refresh=false [status:200 request:14.729s]
2022-02-09 10:05:46.312:INFO:elasticsearch: POST http:/<url>:9200/_bulk?refresh=false [status:200 request:12.743s]
 0:02:10.208489 (130.21 sec)
2022-02-09 10:05:46.489:ERROR:pgsync.base: Exception (psycopg2.errors.UndefinedObject) replication slot "slot_name" does not exist

[SQL: SELECT xid, data 
FROM PG_LOGICAL_SLOT_PEEK_CHANGES(%(PG_LOGICAL_SLOT_PEEK_CHANGES_1)s, NULL, NULL) 
WHERE CAST(CAST(xid AS TEXT) AS BIGINT) < %(param_1)s]
[parameters: {'PG_LOGICAL_SLOT_PEEK_CHANGES_1': 'slot_name', 'param_1': 48325885}]
(Background on this error at: https://sqlalche.me/e/14/f405)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedObject: replication slot "slot_name" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 812, in fetchall
    rows = conn.execute(statement).fetchall()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1491, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2027, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) replication slot "slot_name" does not exist

[SQL: SELECT xid, data 
FROM PG_LOGICAL_SLOT_PEEK_CHANGES(%(PG_LOGICAL_SLOT_PEEK_CHANGES_1)s, NULL, NULL) 
WHERE CAST(CAST(xid AS TEXT) AS BIGINT) < %(param_1)s]
[parameters: {'PG_LOGICAL_SLOT_PEEK_CHANGES_1': 'slot_name', 'param_1': 48325885}]
(Background on this error at: https://sqlalche.me/e/14/f405)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedObject: replication slot "slot_name" does not exist

```

**Comment by Eklavaya** [comment]
ignore it , fixed it at my side
