### ISSUE TITLE
Support for Elasticsearch "flattened" Field Data Type

### ISSUE THREAD

**Issue by rjdlee** [toluaina/pgsync#249]
Operating System: Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-96-generic x86_64)

PGSync version: 2.1.10

Postgres version: 13.5

Elasticsearch version: 7.16.3

Redis version: 5.0.7

Python version: Python 3.8.10

Problem Description: 

I have a lot of custom fields and would like to use the Elasticsearch [flattened field data type](https://www.elastic.co/guide/en/elasticsearch/reference/current/flattened.html). 

If I don't use the flattened field data type, I get the error:
```
'error': {
        'type': 'mapper_parsing_exception',
        'reason': 'failed to parse',
        'caused_by': {
          'type': 'illegal_argument_exception',
          'reason': 'Limit of total fields [1000] has been exceeded while adding new fields [1]'
        }
      },
```

However, I get an error when I set the schema to:
```
"transform": {
  "traits": {
      "type": "flattened"
    }
}
```

Error Message (if any): 
```
Traceback (most recent call last):
  File "~/.local/bin/bootstrap", line 68, in <module>
    main()
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "~/.local/bin/bootstrap", line 58, in main
    document, verbose=verbose, repl_slots=False, **kwargs
  File "~/.local/lib/python3.7/site-packages/pgsync/sync.py", line 102, in __init__
    self.create_setting()
  File "~/.local/lib/python3.7/site-packages/pgsync/sync.py", line 244, in create_setting
    routing=self.routing,
  File "~/.local/lib/python3.7/site-packages/pgsync/elastichelper.py", line 244, in _create_setting
    mapping: dict = self._build_mapping(node, routing)
  File "~/.local/lib/python3.7/site-packages/pgsync/elastichelper.py", line 274, in _build_mapping
    f"Invalid Elasticsearch type {column_type}"
RuntimeError: Invalid Elasticsearch type flattened
```

**Comment by rjdlee** [comment]
I think this is all that's needed to solve the issue?

<img width="1246" alt="Screen Shot 2022-02-13 at 10 06 22 PM" src="https://user-images.githubusercontent.com/8755189/153809163-ce88be22-e977-4114-990f-a0bf537d0d2c.png">

**Comment by toluaina** [comment]
Yes there is a validation for valid field types. Can you add it and verify it does what you want?
If so I can add this, thanks

**Comment by rjdlee** [comment]
@toluaina Yep it works for me when I make the change in the screenshot

**Comment by toluaina** [comment]
I have added this now thanks

**Comment by rjdlee** [comment]
Thanks man, appreciate the help a lot!
