### ISSUE TITLE
Parallel Sync: AttributeError: Can't pickle local object 'create_engine.<locals>.connect'

### ISSUE THREAD

**Issue by rjdlee** [toluaina/pgsync#255]
PGSync version: Latest Commit: https://github.com/toluaina/pgsync/commit/fdaf415ca5da208debb81924abe6d05404fe8701

Postgres version: 13.5

Elasticsearch version: 8.0.0

Redis version: 6.2.6

Python version: 3.8.9

Problem Description: 

I get the following error after running:
```
parallel_sync --config schema.json -n 1
```

Error Message (if any): 

```
2022-02-28 10:06:18.498:INFO:pgsync.utils: Settings:
2022-02-28 10:06:18.498:INFO:pgsync.utils: Schema    : None
2022-02-28 10:06:18.498:INFO:pgsync.utils: -----------------------------------------------------------------
2022-02-28 10:06:18.498:INFO:pgsync.utils: Postgres:
2022-02-28 10:06:18.498:INFO:pgsync.utils: URL: postgresql://pgsync:*****@****
2022-02-28 10:06:18.498:INFO:pgsync.utils: Elasticsearch:
2022-02-28 10:06:18.498:INFO:pgsync.utils: URL: http://elastic:*****@***
2022-02-28 10:06:18.498:INFO:pgsync.utils: Redis:
2022-02-28 10:06:18.498:INFO:pgsync.utils: URL: redis://****
2022-02-28 10:06:18.498:INFO:pgsync.utils: -----------------------------------------------------------------
2022-02-28 10:06:18.504:DEBUG:__main__: ncpus   : 1
2022-02-28 10:06:18.504:DEBUG:pgsync.plugin: Reloading plugins from package: plugins
2022-02-28 10:06:18.509:DEBUG:pgsync.plugin: Reloading plugins from package: plugins
2022-02-28 10:06:18.966:INFO:elasticsearch: GET https://****/ [status:200 request:0.457s]
2022-02-28 10:06:19.040:INFO:elasticsearch: GET https://****/ [status:200 request:0.073s]
2022-02-28 10:06:19.040:DEBUG:pgsync.plugin: Reloading plugins from package: plugins
2022-02-28 10:06:19.041:DEBUG:pgsync.urls: Connecting to Redis without password.
2022-02-28 10:06:19.720:DEBUG:pgsync.plugin: Reloading plugins from package: plugins
2022-02-28 10:06:19.722:DEBUG:pgsync.plugin: Plugin class: plugins.tokens_plugin.TokensPlugins
 - tokens
   |- listings
   |   - transactions
    - collections
2022-02-28 10:06:27.986:INFO:elasticsearch: HEAD https://****/tokens [status:200 request:0.075s]
Query tasks... 0:00:36.871775 (36.87 sec)
2022-02-28 10:07:04.864:DEBUG:__main__: tasks   : 167
2022-02-28 10:07:04.864:DEBUG:pgsync.plugin: Reloading plugins from package: plugins
2022-02-28 10:07:04.866:DEBUG:pgsync.plugin: Reloading plugins from package: plugins
2022-02-28 10:07:05.196:INFO:elasticsearch: GET https://****/ [status:200 request:0.329s]
2022-02-28 10:07:05.270:INFO:elasticsearch: GET https://****/ [status:200 request:0.074s]
2022-02-28 10:07:05.271:DEBUG:pgsync.plugin: Reloading plugins from package: plugins
2022-02-28 10:07:05.271:DEBUG:pgsync.urls: Connecting to Redis without password.
2022-02-28 10:07:06.102:DEBUG:pgsync.plugin: Reloading plugins from package: plugins
2022-02-28 10:07:06.103:DEBUG:pgsync.plugin: Plugin class: plugins.tokens_plugin.TokensPlugins
 - tokens
   |- listings
   |   - transactions
    - collections
2022-02-28 10:07:13.408:INFO:elasticsearch: HEAD https://****/tokens [status:200 request:0.075s]
2022-02-28 10:07:13.409:DEBUG:pgsync.plugin: Reloading plugins from package: plugins
2022-02-28 10:07:13.415:DEBUG:pgsync.plugin: Reloading plugins from package: plugins
2022-02-28 10:07:13.746:INFO:elasticsearch: GET https://****/ [status:200 request:0.330s]
2022-02-28 10:07:13.820:INFO:elasticsearch: GET https://****/ [status:200 request:0.073s]
2022-02-28 10:07:13.820:DEBUG:pgsync.plugin: Reloading plugins from package: plugins
2022-02-28 10:07:13.820:DEBUG:pgsync.urls: Connecting to Redis without password.
2022-02-28 10:07:14.525:DEBUG:pgsync.plugin: Reloading plugins from package: plugins
2022-02-28 10:07:14.525:DEBUG:pgsync.plugin: Plugin class: plugins.tokens_plugin.TokensPlugins
 - tokens
   |- listings
   |   - transactions
    - collections
2022-02-28 10:07:21.877:INFO:elasticsearch: HEAD https://****/tokens [status:200 request:0.073s]
2022-02-28 10:07:22.037:DEBUG:__main__: pull txmin: None - txmax: 17144380
 0:01:03.555797 (63.56 sec)
Traceback (most recent call last):
  File "/Users/rjdlee/src/wagmi-cardano-sync/bin/parallel_sync", line 178, in <module>
    main()
  File "/Users/rjdlee/src/wagmi-cardano-sync/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rjdlee/src/wagmi-cardano-sync/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/rjdlee/src/wagmi-cardano-sync/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rjdlee/src/wagmi-cardano-sync/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/rjdlee/src/wagmi-cardano-sync/bin/parallel_sync", line 174, in main
    pull(ncpus, config, verbose=verbose)
  File "/Users/rjdlee/src/wagmi-cardano-sync/bin/parallel_sync", line 137, in pull
    worker.start()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'create_engine.<locals>.connect'
```

**Comment by toluaina** [comment]
Thanks for that. This is a pickle error that manifests in python 3.8+
I have fixed that in the master branch

**Comment by toluaina** [comment]
Fixed now. Closing
