### ISSUE TITLE
Multiple Postgres schemas are not supported yet

### ISSUE THREAD

**Issue by 97lynk** [toluaina/pgsync#282]
PGSync version: 2.2.1 (pypi)

Postgres version: 14.2

Elasticsearch version: 7.16.2 

Redis version: 5.0.7

Python version: 3.7

Problem Description: 
Hi everyone, 
I have a problem when working with 2 postgres schema.
I have two tables on two postgres schemas (pr.product & li.image_product). Everything is ok until we make changes (update a field/ add new row/ delete a row) in li.image_product.
I found the root cause. So **pr._view** view isn't contains image_product.
<img width="561" alt="image" src="https://user-images.githubusercontent.com/32217548/169651313-abafd08f-f0b1-4fb5-a06a-3fb53b460b43.png">

The temporary solution is to edit **pr._view** view to add a new record.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/32217548/169660218-c16740f8-3e09-49ee-b914-14c818ff0c60.png">

Do you have any comments on this issue?
Thanks,

Error Message (if any): 

```

2022-05-21 12:16:19.286:DEBUG:pgsync.sync: poll_redis: [{'xmin': 729102, 'new': None, 'old': None, 'tg_op': 'UPDATE', 'table': 'image_product', 'schema': 'li'}]
2022-05-21 12:16:19.286:DEBUG:pgsync.sync: poll_redis: [{'xmin': 729102, 'new': None, 'old': None, 'tg_op': 'UPDATE', 'table': 'image_product', 'schema': 'li'}]
2022-05-21 12:16:19.286:DEBUG:pgsync.sync: on_publish len 1
2022-05-21 12:16:19.286:DEBUG:pgsync.sync: on_publish len 1
2022-05-21 12:16:19.311:DEBUG:pgsync.sync: tg_op: UPDATE table: li.image_product
2022-05-21 12:16:19.409:ERROR:pgsync.elastichelper: Exception 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pgsync/elastichelper.py", line 117, in bulk
    raise_on_error=raise_on_error,
  File "/usr/local/lib/python3.7/site-packages/pgsync/elastichelper.py", line 185, in _bulk
    ignore_status=ignore_status,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 484, in parallel_bulk
    actions, chunk_size, max_chunk_bytes, client.transport.serializer
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 140, in _helper_reraises_exception
    raise ex
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 292, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
    for action, data in actions:
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 768, in _payloads
    extra,
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 531, in _update_op
    payload_data[key] for key in node.model.primary_keys
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 531, in <listcomp>
    payload_data[key] for key in node.model.primary_keys
TypeError: 'NoneType' object is not subscriptable

```

**Comment by jyanay** [comment]
Is this limitation by design or is pgsync meant to be able to handle multiple different postgres schemas?

**Comment by toluaina** [comment]
apologies. it was a bug and it has now been fixed in master. 
you'll need to re-run bootstrap for this to take effect

-`bootstrap -c /path/to/schema.json -t`
-` bootstrap -c /path/to/schema.json `

**Comment by jyanay** [comment]
@toluaina Wow thank you!

**Comment by 97lynk** [comment]
> apologies. it was a bug and it has now been fixed in master. you'll need to re-run bootstrap for this to take effect
> 
> -`bootstrap -c /path/to/schema.json -t` -`bootstrap -c /path/to/schema.json`

Thanks Sir <3
