### ISSUE TITLE
Cannot have two children with same table

### ISSUE THREAD

**Issue by patryksliwinski** [toluaina/pgsync#300]
Hello
I have one table that needs to be used twice in children array
The problem is when same table occurs in children, updating is not working
To handle it somehow I had to create 2 same views with only difference as names, so pgsync sees them as different tables.

**Comment by toluaina** [comment]
yes this is a known issue. I will address this together with [this](https://github.com/toluaina/pgsync/issues/296) issue as there are slightly related

**Comment by bhalonen** [comment]
@toluaina Think I'm running into the same issue, the initial load out of existing data works, but then updates fail. Will try the view approach to hack around for now.

**Comment by tdeverdiere** [comment]
I tried the workaround like this: 
- i create 2 sql views with different names that are referencing the same table.
But when i start pgsync, i have the following error:
```
ERROR:pgsync.sync: Exception invalid expression
pgsync               | Traceback (most recent call last):
pgsync               |   File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 968, in sync
pgsync               |     self.query_builder.build_queries(node)
pgsync               |   File "/usr/local/lib/python3.10/site-packages/pgsync/querybuilder.py", line 723, in build_queries
pgsync               |     self._non_through(node)
pgsync               |   File "/usr/local/lib/python3.10/site-packages/pgsync/querybuilder.py", line 648, in _non_through
pgsync               |     node, sa.func.JSON_AGG(self._json_build_object(params))
pgsync               |   File "/usr/local/lib/python3.10/site-packages/pgsync/querybuilder.py", line 50, in _json_build_object
pgsync               |     raise RuntimeError("invalid expression")
pgsync               | RuntimeError: invalid expression
pgsync               | 2022-09-07 13:38:47.363:ERROR:pgsync.elastichelper: Exception invalid expression
pgsync               | Traceback (most recent call last):
pgsync               |   File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 130, in bulk
```
[test_files.zip](https://github.com/toluaina/pgsync/files/9506695/test_files.zip)
I attached those test files that contains SQL instructions and the `schema.json`

**Comment by tdeverdiere** [comment]
Is it possible to have a working sample with view? I feel it is not possible in certain case. For example when the child table owns the relation, then i believe a trigger is set on the child table. But postgresql complains about trigger on view: "Views cannot have row-level BEFORE or AFTER triggers".
