### ISSUE TITLE
Missing documentation about importing plugin from pgsync

### ISSUE THREAD

**Issue by hookenful** [toluaina/pgsync#307]
Hi there!

I suppose, you have lack of documentation in case of applying plugins. You write:

```

class FullnamePlugin(plugin.Plugin):
    name = 'Fullname'

    def transform(self, doc, **kwargs):

        firstname = doc['firstname'] 
        lastname = doc['lastname'] 
        doc['fullname'] = f'{firstname}{lastname}'

        return doc
```

But there is nothing about `from pgsync import plugin`. And without it I am having error about plugin is not defined.

After I add import, all became OK.

But I have another, not related problem here. I am not much familiar with python. I have such plugin:

```
class FullnamePlugin(plugin.Plugin):
    name = 'Fullname'

    def transform(self, doc, **kwargs):

        firstname = filter(lambda field: field["FieldId"] == "f5f67cb3-c7e6-42a9-a299-06511240bda0", doc["UserField"])
        lastname = filter(lambda field: field["FieldId"] == "43bf99f4-20cf-48c3-9d09-d4488e9f0933", doc["UserField"])
        middlename = filter(lambda field: field["FieldId"] == "7148b419-7900-44b3-85dd-3e8bb556956e", doc["UserField"])
        doc['fullname'] = f'{firstname}{lastname}{middlename}'

        return doc
```

But I am having that error. What did I miss there? 

```
2022-07-06 11:49:46.500:ERROR:pgsync.elastichelper: Exception 'UserField'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 105, in bulk
    self._bulk(
  File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 175, in _bulk
    for _ in helpers.parallel_bulk(
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 472, in parallel_bulk
    for result in pool.imap(
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
    for action, data in actions:
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 949, in sync
    doc = next(self._plugins.transform([doc]))
  File "/usr/local/lib/python3.10/site-packages/pgsync/plugin.py", line 79, in transform
    doc["_source"] = plugin.transform(
  File "/usr/src/app/plugins/fullnameplugin.py", line 8, in transform
    firstname = filter(lambda field: field["FieldId"] == "f5f67cb3-c7e6-42a9-a299-06511240bda0", doc["UserField"])
KeyError: 'UserField'
 0:00:03.019468 (3.02 sec)
Traceback (most recent call last):
  File "/usr/local/bin/pgsync", line 7, in <module>
    sync.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 1249, in main
    sync.pull()
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 1080, in pull
    self.es.bulk(self.index, self.sync(txmin=txmin, txmax=txmax))
  File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 105, in bulk
    self._bulk(
  File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 175, in _bulk
    for _ in helpers.parallel_bulk(
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 472, in parallel_bulk
    for result in pool.imap(
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
    for action, data in actions:
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 949, in sync
    doc = next(self._plugins.transform([doc]))
  File "/usr/local/lib/python3.10/site-packages/pgsync/plugin.py", line 79, in transform
    doc["_source"] = plugin.transform(
  File "/usr/src/app/plugins/fullnameplugin.py", line 8, in transform
    firstname = filter(lambda field: field["FieldId"] == "f5f67cb3-c7e6-42a9-a299-06511240bda0", doc["UserField"])
KeyError: 'UserField'
```

My document
```
{
  "_index": "users",
  "_type": "_doc",
  "_id": "07e4588c-6102-4be2-9518-cabaa40726e0",
  "_score": 1,
  "_source": {
    "UserId": "07e4588c-6102-4be2-9518-cabaa40726e0",
...
    "UserField": [
      {
        "Id": "3fa8f6aa-e4d7-4762-9287-d53de515954a",
        "Value": "",
        "UserId": "07e4588c-6102-4be2-9518-cabaa40726e0",
        "FieldId": "3acca766-9f4a-4d7e-9ffb-262b7a26c971",
        "TenantKey": "b1ef9a58-bcbf-4069-ae4a-3efea1a51bba"
      },
      {
        "Id": "7b9219c7-4157-465c-9904-4e529cbf2f66",
        "Value": "Mason",
        "UserId": "07e4588c-6102-4be2-9518-cabaa40726e0",
        "FieldId": "f5f67cb3-c7e6-42a9-a299-06511240bda0",
        "TenantKey": "b1ef9a58-bcbf-4069-ae4a-3efea1a51bba"
      },
      {
        "Id": "b65ba0e9-64b7-4203-8ac1-0984dad642a5",
        "Value": "Alex",
        "UserId": "07e4588c-6102-4be2-9518-cabaa40726e0",
        "FieldId": "43bf99f4-20cf-48c3-9d09-d4488e9f0933",
        "TenantKey": "b1ef9a58-bcbf-4069-ae4a-3efea1a51bba"
      },
}
    ],
...
      }
    }
  }
}
```

**Comment by hookenful** [comment]
I've changed it for 
```
from pgsync import plugin

class FullnamePlugin(plugin.Plugin):
    name = 'Fullname'

    def transform(self, doc, **kwargs):
        print(next(filter(lambda field: field["FieldId"] == "f5f67cb3-c7e6-42a9-a299-06511240bda0", doc["UserField"])))
        firstname = next(filter(lambda field: field["FieldId"] == "f5f67cb3-c7e6-42a9-a299-06511240bda0", doc["UserField"])).Value
        lastname = next(filter(lambda field: field["FieldId"] == "43bf99f4-20cf-48c3-9d09-d4488e9f0933", doc["UserField"])).Value
        middlename = next(filter(lambda field: field["FieldId"] == "7148b419-7900-44b3-85dd-3e8bb556956e", doc["UserField"])).Value
        doc['fullname'] = f'{firstname}{lastname}{middlename}'

        return doc
```


And now getting another error,
```
Traceback (most recent call last):
  File "/usr/local/bin/pgsync", line 7, in <module>
    sync.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 1249, in main
    sync.pull()
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 1080, in pull
    self.es.bulk(self.index, self.sync(txmin=txmin, txmax=txmax))
  File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 105, in bulk
    self._bulk(
  File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 175, in _bulk
    for _ in helpers.parallel_bulk(
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 472, in parallel_bulk
    for result in pool.imap(
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
    for action, data in actions:
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 949, in sync
    doc = next(self._plugins.transform([doc]))
  File "/usr/local/lib/python3.10/site-packages/pgsync/plugin.py", line 79, in transform
    doc["_source"] = plugin.transform(
  File "/usr/src/app/plugins/fullnameplugin.py", line 8, in transform
    firstname = next(filter(lambda field: field["FieldId"] == "f5f67cb3-c7e6-42a9-a299-06511240bda0", doc["UserField"])).Value
AttributeError: 'dict' object has no attribute 'Value'. Did you mean: 'values'?
```

**Comment by hookenful** [comment]
Got it fixed. 

Our frontend saying, there is a some delay between syncing. Should I use lower POLL_TIMEOUT for the effect? 

And what about NTHREADS_POLLDB ? Can it help aswell as poll timeout?

**Comment by toluaina** [comment]
> Got it fixed.
> 
> Our frontend saying, there is a some delay between syncing. Should I use lower POLL_TIMEOUT for the effect?
> 
> And what about NTHREADS_POLLDB ? Can it help aswell as poll timeout?

How long is the delay and how many records?
It would be better to have this in a separate issue for clarity

**Comment by hookenful** [comment]
> > Got it fixed.
> > Our frontend saying, there is a some delay between syncing. Should I use lower POLL_TIMEOUT for the effect?
> > And what about NTHREADS_POLLDB ? Can it help aswell as poll timeout?
> 
> How long is the delay and how many records? It would be better to have this in a separate issue for clarity

Approx 300-500 msec. 1 record

**Comment by hookenful** [comment]
Can you add in discord please? I've sent an invite hoozR#9863

**Comment by hookenful** [comment]
Can you suggest complex of best settings for highest throughoutput ? No matter of resources, as we have 12 logical CPU on cluster.
