### ISSUE TITLE
Pgsync container dies when I add new data to Postges

### ISSUE THREAD

**Issue by goktugbati** [toluaina/pgsync#321]
Problem Description: When I run the containers for the first time it syncs without any problem but when I add new data to postgres pgsync container logs the error below and the container dies but surprisingly it syncs when I restart the container

Error Message (if any): 
2022-07-28 10:07:18.053:ERROR:pgsync.elastichelper: Exception Select statement '<sqlalchemy.sql.selectable.Select object at 0x7f4f91a36810>' returned no FROM clauses due to auto-correlation; specify correlate(<tables>) to control correlation manually.
2022-07-28T10:07:18.119073800Z Traceback (most recent call last):
2022-07-28T10:07:18.119083000Z   File "/usr/local/lib/python3.7/site-packages/pgsync/elastichelper.py", line 142, in bulk
2022-07-28T10:07:18.119086700Z     raise_on_error=raise_on_error,
2022-07-28T10:07:18.119089400Z   File "/usr/local/lib/python3.7/site-packages/pgsync/elastichelper.py", line 197, in _bulk
2022-07-28T10:07:18.119092500Z     ignore_status=ignore_status,
2022-07-28T10:07:18.119095400Z   File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 484, in parallel_bulk
2022-07-28T10:07:18.119098100Z     actions, chunk_size, max_chunk_bytes, client.transport.serializer
2022-07-28T10:07:18.119101000Z   File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 748, in next
2022-07-28T10:07:18.119103900Z     raise value
2022-07-28T10:07:18.119106700Z   File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
2022-07-28T10:07:18.119109500Z     result = (True, func(*args, **kwds))
2022-07-28T10:07:18.119112100Z   File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 140, in _helper_reraises_exception
2022-07-28T10:07:18.119114700Z     raise ex
2022-07-28T10:07:18.119117400Z   File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 292, in _guarded_task_generation
2022-07-28T10:07:18.119120100Z     for i, x in enumerate(iterable):
2022-07-28T10:07:18.119122800Z   File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
2022-07-28T10:07:18.119125700Z     for action, data in actions:
2022-07-28T10:07:18.119128700Z   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 851, in _payloads
2022-07-28T10:07:18.119131500Z     yield from self.sync(filters=filters, extra=extra)
2022-07-28T10:07:18.119142200Z   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 966, in sync
2022-07-28T10:07:18.119144800Z     count: int = self.fetchcount(node._subquery)
2022-07-28T10:07:18.119147200Z   File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 800, in fetchcount
2022-07-28T10:07:18.119149500Z     ).order_by(None)
2022-07-28T10:07:18.119151900Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1306, in execute
2022-07-28T10:07:18.119154400Z     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
2022-07-28T10:07:18.119156900Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
2022-07-28T10:07:18.119159600Z     self, multiparams, params, execution_options
2022-07-28T10:07:18.119163700Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1496, in _execute_clauseelement
2022-07-28T10:07:18.119166200Z     linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
2022-07-28T10:07:18.119168500Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 536, in _compile_w_cache
2022-07-28T10:07:18.119170800Z     **kw
2022-07-28T10:07:18.119173200Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 565, in _compiler
2022-07-28T10:07:18.119175700Z     return dialect.statement_compiler(dialect, self, **kw)
2022-07-28T10:07:18.119178100Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 778, in __init__
2022-07-28T10:07:18.119180500Z     Compiled.__init__(self, dialect, statement, **kwargs)
2022-07-28T10:07:18.119182700Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 451, in __init__
2022-07-28T10:07:18.119185000Z     self.string = self.process(self.statement, **compile_kwargs)
2022-07-28T10:07:18.119187400Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 486, in process
2022-07-28T10:07:18.119189600Z     return obj._compiler_dispatch(self, **kwargs)
2022-07-28T10:07:18.119192000Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2022-07-28T10:07:18.119194600Z     return meth(self, **kw)
2022-07-28T10:07:18.119196900Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3428, in visit_select
2022-07-28T10:07:18.119199400Z     kwargs,
2022-07-28T10:07:18.119201500Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3571, in _compose_select_body
2022-07-28T10:07:18.119203900Z     for f in froms
2022-07-28T10:07:18.119206100Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3571, in <listcomp>
2022-07-28T10:07:18.119208600Z     for f in froms
2022-07-28T10:07:18.119210900Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2022-07-28T10:07:18.119216300Z     return meth(self, **kw)
2022-07-28T10:07:18.119218800Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3811, in visit_join
2022-07-28T10:07:18.119223300Z     + join.onclause._compiler_dispatch(
2022-07-28T10:07:18.119225500Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2022-07-28T10:07:18.119227800Z     return meth(self, **kw)
2022-07-28T10:07:18.119230000Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3811, in visit_join
2022-07-28T10:07:18.119232300Z     + join.onclause._compiler_dispatch(
2022-07-28T10:07:18.119234900Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2022-07-28T10:07:18.119237400Z     return meth(self, **kw)
2022-07-28T10:07:18.119239800Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2938, in visit_lateral
2022-07-28T10:07:18.119242200Z     return "LATERAL %s" % self.visit_alias(lateral_, **kw)
2022-07-28T10:07:18.119244500Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2894, in visit_alias
2022-07-28T10:07:18.119246800Z     self, asfrom=True, lateral=lateral, **kwargs
2022-07-28T10:07:18.119249000Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2022-07-28T10:07:18.119251300Z     return meth(self, **kw)
2022-07-28T10:07:18.119253700Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2934, in visit_subquery
2022-07-28T10:07:18.119256100Z     return self.visit_alias(subquery, **kw)
2022-07-28T10:07:18.119258400Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2873, in visit_alias
2022-07-28T10:07:18.119260900Z     **kwargs
2022-07-28T10:07:18.119263100Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2022-07-28T10:07:18.119265300Z     return meth(self, **kw)
2022-07-28T10:07:18.119267500Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3428, in visit_select
2022-07-28T10:07:18.119269800Z     kwargs,
2022-07-28T10:07:18.119272100Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3571, in _compose_select_body
2022-07-28T10:07:18.119274600Z     for f in froms
2022-07-28T10:07:18.119276900Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3571, in <listcomp>
2022-07-28T10:07:18.119279500Z     for f in froms
2022-07-28T10:07:18.119281700Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2022-07-28T10:07:18.119283900Z     return meth(self, **kw)
2022-07-28T10:07:18.119286100Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3811, in visit_join
2022-07-28T10:07:18.119290800Z     + join.onclause._compiler_dispatch(
2022-07-28T10:07:18.119293300Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2022-07-28T10:07:18.119295800Z     return meth(self, **kw)
2022-07-28T10:07:18.119298100Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2938, in visit_lateral
2022-07-28T10:07:18.119300600Z     return "LATERAL %s" % self.visit_alias(lateral_, **kw)
2022-07-28T10:07:18.119302800Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2894, in visit_alias
2022-07-28T10:07:18.119305100Z     self, asfrom=True, lateral=lateral, **kwargs
2022-07-28T10:07:18.119307500Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2022-07-28T10:07:18.119309900Z     return meth(self, **kw)
2022-07-28T10:07:18.119312300Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2934, in visit_subquery
2022-07-28T10:07:18.119314800Z     return self.visit_alias(subquery, **kw)
2022-07-28T10:07:18.119317200Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2873, in visit_alias
2022-07-28T10:07:18.119319600Z     **kwargs
2022-07-28T10:07:18.119321800Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
2022-07-28T10:07:18.119324100Z     return meth(self, **kw)
2022-07-28T10:07:18.119326300Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3332, in visit_select
2022-07-28T10:07:18.119328600Z     select_stmt, compile_state, entry, asfrom, lateral, compound_index
2022-07-28T10:07:18.119331100Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3508, in _setup_select_stack
2022-07-28T10:07:18.119333500Z     implicit_correlate_froms=asfrom_froms,
2022-07-28T10:07:18.119335900Z   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 4588, in _get_display_froms
2022-07-28T10:07:18.119338400Z     "manually." % self.statement
2022-07-28T10:07:18.119340700Z sqlalchemy.exc.InvalidRequestError: Select statement '<sqlalchemy.sql.selectable.Select object at 0x7f4f91a36810>' returned no FROM clauses due to auto-correlation; specify correlate(<tables>) to control correlation manually.

**Comment by niraj-ads** [comment]
@goktugbati, encountered the same problem!
https://github.com/toluaina/pgsync/issues/264
