### ISSUE TITLE
Index field in schema is not optional

### ISSUE THREAD

**Issue by niklhut** [toluaina/pgsync#335]
PGSync version:  2.3.2

Postgres version: 14

Elasticsearch version: 8.4.1

Redis version: 7.0.4

Python version: 3.7

### Problem Description: 

The [docs state that the index field in the schema is optional and defaults to the database name when not set.](https://pgsync.com/schema/#index). 

However, when not setting the index field PGSync exits with code 1.

#### Error Message (if any): 

```
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/bin/bootstrap", line 70, in <module>
pgsync_1         |     main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
pgsync_1         |     return __callback(*args, **kwargs)
pgsync_1         |   File "/usr/local/bin/bootstrap", line 58, in main
pgsync_1         |     for document in json.load(open(config)):
pgsync_1         |   File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
pgsync_1         |     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
pgsync_1         |   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
pgsync_1         |     return _default_decoder.decode(s)
pgsync_1         |   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
pgsync_1         |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
pgsync_1         |   File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
pgsync_1         |     obj, end = self.scan_once(s, idx)
pgsync_1         | json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 4 column 9 (char 54)
pgsync_1         |  0:00:00.001140 (0.00 sec)
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/bin/pgsync", line 7, in <module>
pgsync_1         |     sync.main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
pgsync_1         |     return __callback(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 1409, in main
pgsync_1         |     for document in json.load(open(config)):
pgsync_1         |   File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
pgsync_1         |     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
pgsync_1         |   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
pgsync_1         |     return _default_decoder.decode(s)
pgsync_1         |   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
pgsync_1         |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
pgsync_1         |   File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
pgsync_1         |     obj, end = self.scan_once(s, idx)
pgsync_1         | json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 4 column 9 (char 54)
pgsync_1 exited with code 1
```

### Workaround:

Set the index field in the `schema.json` file.

**Comment by toluaina** [comment]
This has now been fixed in the main branch. Thanks for spotting this

**Comment by toluaina** [comment]
closing as resolved
