### ISSUE TITLE
Error syncing up when materialized view record no longer exists or removed

### ISSUE THREAD

**Issue by camilomontoyau** [toluaina/pgsync#338]
PGSync version: 2.3.2

Postgres version: 13.2

Elasticsearch version: 7.17.4

Redis version: 7.0.4

Python version: 3.10.6

Problem Description: 
I'm only mapping a materialized view, this materialized view has a unique index but, from what I know, materialized views can't have primary keys
Error happens when materialized view is refreshed and one or some of its records disappeared or got removed.
I'm noticing that pgsync only checks for primary keys but it doesn't check for unique keys which makes it throw an error when trying to remove the deleted record from elasticsearch

![Screen Shot 2022-09-01 at 9 52 13 AM](https://user-images.githubusercontent.com/5333383/187959780-174ca9c9-d8b5-4227-9376-344f2722ad42.png)

Error Message (if any): 

```
2022-09-01 15:35:01.878:ERROR:pgsync.elastichelper: Exception 'id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 130, in bulk
    self._bulk(
  File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 187, in _bulk
    for _ in helpers.parallel_bulk(
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 472, in parallel_bulk
    for result in pool.imap(
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 391, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
    for action, data in actions:
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 841, in _payloads
    filters = self._delete_op(
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 666, in _delete_op
    self.root_primary_values: list = [
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 667, in <listcomp>
    payload_data[key] for key in self.root.model.primary_keys
KeyError: 'id'
 0:00:00.233008 (0.23 sec)
Traceback (most recent call last):
  File "/usr/local/bin/pgsync", line 7, in <module>
    sync.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 1416, in main
    sync.pull()
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 1221, in pull
    self.logical_slot_changes(txmin=txmin, txmax=txmax)
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 435, in logical_slot_changes
    self.es.bulk(self.index, self._payloads(payloads))
  File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 130, in bulk
    self._bulk(
  File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 187, in _bulk
    for _ in helpers.parallel_bulk(
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 472, in parallel_bulk
    for result in pool.imap(
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 391, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
    for action, data in actions:
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 841, in _payloads
    filters = self._delete_op(
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 666, in _delete_op
    self.root_primary_values: list = [
  File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 667, in <listcomp>
    payload_data[key] for key in self.root.model.primary_keys
KeyError: 'id'
```

**Comment by toluaina** [comment]
So you suggesting that you deleted a row and this was not deleted in Elasticsearch?
Are you able to put together a working example?
Are you manually changing the materialized view?
