### ISSUE TITLE
Join with jsonb column

### ISSUE THREAD

**Issue by rutkowskib** [toluaina/pgsync#342]
PGSync version: 
2.3.2
Postgres version: 
13.4
Elasticsearch version: 
OpenSearch 1.2.4(Elasticsearch 7.10 compatible)
Redis version: 
6.2
Python version: 
3.10
Problem Description: 

Hi,
I am trying to do a join of jsonb field containing an array of UUIDs with child that has UUID type id. To visualize I am trying to achieve something like this:

```
Rooms(in Postgres):
id | users
6fc9bb54-0d74-45de-808f-b349417bf958  | ["01e14b1b-bfe4-48da-a39b-53085a8f6891"]

Product(in Postgres)
id | name
01e14b1b-bfe4-48da-a39b-53085a8f6891 | name

Rooms(in ElasticSearch)
id | users
6fc9bb54-0d74-45de-808f-b349417bf958 | [{ "id": "01e14b1b-bfe4-48da-a39b-53085a8f6891", "name": "name" }]
```
My schema.json looks like this:
```
{
  "database": "{{database}}",
  "index": "rooms",
  "nodes": {
    "table": "rooms",
    "schema": "social",
    "columns": [
      "id",
      "productsJson"
    ],
    "children": [{
      "table": "product",
      "schema": "social",
      "relationship": {
        "variant": "object",
        "type": "one_to_many",
        "foreign_key": {
          "child": ["id"],
          "parent": ["productsJson"]
        }
      }
    }]
  }
}
```
When I try to do this I get an error below. Is there any way to implement it in the current version? If not, do you think it is achievable to have this added? I could do some work on this.

Thank you for your help and work on this tool.

Error Message (if any): 

```
docker-local-pgsync-1      | 2022-09-21 10:47:10.972:ERROR:pgsync.elastichelper: Exception (psycopg2.errors.UndefinedFunction) operator does not exist: uuid = jsonb
docker-local-pgsync-1      | LINE 4: WHERE product_1.id = rooms_1."productsJson" GROUP BY product...
docker-local-pgsync-1      |                            ^
docker-local-pgsync-1      | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
docker-local-pgsync-1      | 
docker-local-pgsync-1      | [SQL: SELECT count(*) AS count_1 
docker-local-pgsync-1      | FROM social.rooms AS rooms_1 LEFT OUTER JOIN LATERAL (SELECT CAST(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_1)s, JSON_AGG(CAST(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_2)s, JSON_BUILD_ARRAY(product_1.id)) AS JSONB))) AS JSONB) AS _keys, JSON_AGG(CAST(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_3)s, product_1.created_at, %(JSON_BUILD_OBJECT_4)s, product_1.updated_at, %(JSON_BUILD_OBJECT_5)s, product_1.version, %(JSON_BUILD_OBJECT_6)s, product_1.id, %(JSON_BUILD_OBJECT_7)s, product_1.name) AS JSONB)) AS product, product_1.id AS id 
docker-local-pgsync-1      | FROM social.product AS product_1 
docker-local-pgsync-1      | WHERE product_1.id = rooms_1."productsJson" GROUP BY product_1.id) AS anon_1 ON anon_1.id = rooms_1."productsJson" 
docker-local-pgsync-1      | WHERE CAST(CAST(rooms_1.xmin AS TEXT) AS BIGINT) < %(param_1)s]
docker-local-pgsync-1      | [parameters: {'JSON_BUILD_OBJECT_1': 'product', 'JSON_BUILD_OBJECT_2': 'id', 'JSON_BUILD_OBJECT_3': 'created_at', 'JSON_BUILD_OBJECT_4': 'updated_at', 'JSON_BUILD_OBJECT_5': 'version', 'JSON_BUILD_OBJECT_6': 'id', 'JSON_BUILD_OBJECT_7': 'name', 'param_1': 1455}]
docker-local-pgsync-1      | (Background on this error at: https://sqlalche.me/e/14/f405)
docker-local-pgsync-1      | Traceback (most recent call last):
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
docker-local-pgsync-1      |     self.dialect.do_execute(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
docker-local-pgsync-1      |     cursor.execute(statement, parameters)
docker-local-pgsync-1      | psycopg2.errors.UndefinedFunction: operator does not exist: uuid = jsonb
docker-local-pgsync-1      | LINE 4: WHERE product_1.id = rooms_1."productsJson" GROUP BY product...
docker-local-pgsync-1      |                            ^
docker-local-pgsync-1      | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
docker-local-pgsync-1      | 
docker-local-pgsync-1      | 
docker-local-pgsync-1      | The above exception was the direct cause of the following exception:
docker-local-pgsync-1      | 
docker-local-pgsync-1      | Traceback (most recent call last):
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 130, in bulk
docker-local-pgsync-1      |     self._bulk(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 187, in _bulk
docker-local-pgsync-1      |     for _ in helpers.parallel_bulk(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 472, in parallel_bulk
docker-local-pgsync-1      |     for result in pool.imap(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 870, in next
docker-local-pgsync-1      |     raise value
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
docker-local-pgsync-1      |     result = (True, func(*args, **kwds))
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 144, in _helper_reraises_exception
docker-local-pgsync-1      |     raise ex
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 388, in _guarded_task_generation
docker-local-pgsync-1      |     for i, x in enumerate(iterable):
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
docker-local-pgsync-1      |     for action, data in actions:
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 966, in sync
docker-local-pgsync-1      |     count: int = self.fetchcount(node._subquery)
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/pgsync/base.py", line 797, in fetchcount
docker-local-pgsync-1      |     return conn.execute(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1306, in execute
docker-local-pgsync-1      |     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
docker-local-pgsync-1      |     return connection._execute_clauseelement(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
docker-local-pgsync-1      |     ret = self._execute_context(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
docker-local-pgsync-1      |     self._handle_dbapi_exception(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
docker-local-pgsync-1      |     util.raise_(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
docker-local-pgsync-1      |     raise exception
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
docker-local-pgsync-1      |     self.dialect.do_execute(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
docker-local-pgsync-1      |     cursor.execute(statement, parameters)
docker-local-pgsync-1      | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: uuid = jsonb
docker-local-pgsync-1      | LINE 4: WHERE product_1.id = rooms_1."productsJson" GROUP BY product...
docker-local-pgsync-1      |                            ^
docker-local-pgsync-1      | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
docker-local-pgsync-1      | 
docker-local-pgsync-1      | [SQL: SELECT count(*) AS count_1 
docker-local-pgsync-1      | FROM social.rooms AS rooms_1 LEFT OUTER JOIN LATERAL (SELECT CAST(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_1)s, JSON_AGG(CAST(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_2)s, JSON_BUILD_ARRAY(product_1.id)) AS JSONB))) AS JSONB) AS _keys, JSON_AGG(CAST(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_3)s, product_1.created_at, %(JSON_BUILD_OBJECT_4)s, product_1.updated_at, %(JSON_BUILD_OBJECT_5)s, product_1.version, %(JSON_BUILD_OBJECT_6)s, product_1.id, %(JSON_BUILD_OBJECT_7)s, product_1.name) AS JSONB)) AS product, product_1.id AS id 
docker-local-pgsync-1      | FROM social.product AS product_1 
docker-local-pgsync-1      | WHERE product_1.id = rooms_1."productsJson" GROUP BY product_1.id) AS anon_1 ON anon_1.id = rooms_1."productsJson" 
docker-local-pgsync-1      | WHERE CAST(CAST(rooms_1.xmin AS TEXT) AS BIGINT) < %(param_1)s]
docker-local-pgsync-1      | [parameters: {'JSON_BUILD_OBJECT_1': 'product', 'JSON_BUILD_OBJECT_2': 'id', 'JSON_BUILD_OBJECT_3': 'created_at', 'JSON_BUILD_OBJECT_4': 'updated_at', 'JSON_BUILD_OBJECT_5': 'version', 'JSON_BUILD_OBJECT_6': 'id', 'JSON_BUILD_OBJECT_7': 'name', 'param_1': 1455}]
docker-local-pgsync-1      | (Background on this error at: https://sqlalche.me/e/14/f405)
docker-local-pgsync-1      |  - social.rooms
docker-local-pgsync-1      |     - social.product
docker-local-pgsync-1      |  0:00:01.243408 (1.24 sec)
docker-local-pgsync-1      | Traceback (most recent call last):
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
docker-local-pgsync-1      |     self.dialect.do_execute(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
docker-local-pgsync-1      |     cursor.execute(statement, parameters)
docker-local-pgsync-1      | psycopg2.errors.UndefinedFunction: operator does not exist: uuid = jsonb
docker-local-pgsync-1      | LINE 4: WHERE product_1.id = rooms_1."productsJson" GROUP BY product...
docker-local-pgsync-1      |                            ^
docker-local-pgsync-1      | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
docker-local-pgsync-1      | 
docker-local-pgsync-1      | 
docker-local-pgsync-1      | The above exception was the direct cause of the following exception:
docker-local-pgsync-1      | 
docker-local-pgsync-1      | Traceback (most recent call last):
docker-local-pgsync-1      |   File "/usr/local/bin/pgsync", line 7, in <module>
docker-local-pgsync-1      |     sync.main()
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
docker-local-pgsync-1      |     return self.main(*args, **kwargs)
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
docker-local-pgsync-1      |     rv = self.invoke(ctx)
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
docker-local-pgsync-1      |     return ctx.invoke(self.callback, **ctx.params)
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
docker-local-pgsync-1      |     return __callback(*args, **kwargs)
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 1400, in main
docker-local-pgsync-1      |     sync.pull()
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 1203, in pull
docker-local-pgsync-1      |     self.es.bulk(self.index, self.sync(txmin=txmin, txmax=txmax))
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 130, in bulk
docker-local-pgsync-1      |     self._bulk(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/pgsync/elastichelper.py", line 187, in _bulk
docker-local-pgsync-1      |     for _ in helpers.parallel_bulk(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 472, in parallel_bulk
docker-local-pgsync-1      |     for result in pool.imap(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 870, in next
docker-local-pgsync-1      |     raise value
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
docker-local-pgsync-1      |     result = (True, func(*args, **kwds))
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 144, in _helper_reraises_exception
docker-local-pgsync-1      |     raise ex
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 388, in _guarded_task_generation
docker-local-pgsync-1      |     for i, x in enumerate(iterable):
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
docker-local-pgsync-1      |     for action, data in actions:
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/pgsync/sync.py", line 966, in sync
docker-local-pgsync-1      |     count: int = self.fetchcount(node._subquery)
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/pgsync/base.py", line 797, in fetchcount
docker-local-pgsync-1      |     return conn.execute(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1306, in execute
docker-local-pgsync-1      |     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
docker-local-pgsync-1      |     return connection._execute_clauseelement(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
docker-local-pgsync-1      |     ret = self._execute_context(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
docker-local-pgsync-1      |     self._handle_dbapi_exception(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
docker-local-pgsync-1      |     util.raise_(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
docker-local-pgsync-1      |     raise exception
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
docker-local-pgsync-1      |     self.dialect.do_execute(
docker-local-pgsync-1      |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
docker-local-pgsync-1      |     cursor.execute(statement, parameters)
docker-local-pgsync-1      | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: uuid = jsonb
docker-local-pgsync-1      | LINE 4: WHERE product_1.id = rooms_1."productsJson" GROUP BY product...
docker-local-pgsync-1      |                            ^
docker-local-pgsync-1      | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
docker-local-pgsync-1      | 
docker-local-pgsync-1      | [SQL: SELECT count(*) AS count_1 
docker-local-pgsync-1      | FROM social.rooms AS rooms_1 LEFT OUTER JOIN LATERAL (SELECT CAST(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_1)s, JSON_AGG(CAST(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_2)s, JSON_BUILD_ARRAY(product_1.id)) AS JSONB))) AS JSONB) AS _keys, JSON_AGG(CAST(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_3)s, product_1.created_at, %(JSON_BUILD_OBJECT_4)s, product_1.updated_at, %(JSON_BUILD_OBJECT_5)s, product_1.version, %(JSON_BUILD_OBJECT_6)s, product_1.id, %(JSON_BUILD_OBJECT_7)s, product_1.name) AS JSONB)) AS product, product_1.id AS id 
docker-local-pgsync-1      | FROM social.product AS product_1 
docker-local-pgsync-1      | WHERE product_1.id = rooms_1."productsJson" GROUP BY product_1.id) AS anon_1 ON anon_1.id = rooms_1."productsJson" 
docker-local-pgsync-1      | WHERE CAST(CAST(rooms_1.xmin AS TEXT) AS BIGINT) < %(param_1)s]
docker-local-pgsync-1      | [parameters: {'JSON_BUILD_OBJECT_1': 'product', 'JSON_BUILD_OBJECT_2': 'id', 'JSON_BUILD_OBJECT_3': 'created_at', 'JSON_BUILD_OBJECT_4': 'updated_at', 'JSON_BUILD_OBJECT_5': 'version', 'JSON_BUILD_OBJECT_6': 'id', 'JSON_BUILD_OBJECT_7': 'name', 'param_1': 1455}]
docker-local-pgsync-1      | (Background on this error at: https://sqlalche.me/e/14/f405)

```

**Comment by toluaina** [comment]
This seems like an anti-relational pattern so I'm not sure how to generalize this.
Your join condition is based on the value of an array.
Do you have any foreign key constraint on these tables and how are they defined.

**Comment by rutkowskib** [comment]
Hi,

No, we don't have any foreign keys for those, because we wanted to keep them separated because we will probably want to migrate them to separate databases. After some debate in our team, we decided that we will create a junction table and proceed using the relationship with through table feature.

I will close this issue.
