### ISSUE TITLE
'Sync' object has no attribute 'model'

### ISSUE THREAD

**Issue by goktugbati** [toluaina/pgsync#360]
PGSync version: latest

Postgres version: 

Elasticsearch version: 7.14.2

Redis version:  latest

Python version: 3.7

Problem Description:  When I run it locally with docker compose it works as expected but pgsync fails with
error when it is deployed to openshift and gives the error below. 

Error Message (if any): 

/usr/local/lib/python3.7/site-packages/pgsync/base.py:170: SAWarning: Skipped unsupported reflection of expression-based index idx_jhi_user_email_lower
metadata.reflect(self.engine, views=True)
/usr/local/lib/python3.7/site-packages/pgsync/base.py:170: SAWarning: Skipped unsupported reflection of expression-based index idx_jhi_user_first_name_lower
metadata.reflect(self.engine, views=True)
/usr/local/lib/python3.7/site-packages/pgsync/base.py:170: SAWarning: Skipped unsupported reflection of expression-based index idx_jhi_user_last_name_lower
metadata.reflect(self.engine, views=True)
 - public.form
Traceback (most recent call last):
File "/usr/local/bin/bootstrap", line 70, in <module>
main()
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "/usr/local/bin/bootstrap", line 60, in main
document, verbose=verbose, repl_slots=False, **kwargs
File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 107, in __init__
self.validate(repl_slots=repl_slots)
File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 197, in validate
model: sa.sql.Alias = self.model(table, node.schema)
AttributeError: 'Sync' object has no attribute 'model'

**Comment by toluaina** [comment]
Sorry about that. This was fixed a while ago. I've published a new version 2.3.3 containing this bug fix.

**Comment by goktugbati** [comment]
thanks, it worked as expected with the new version
