### ISSUE TITLE
Front end not working at port 8000

### ISSUE THREAD

**Issue by lisawebcoder** [toluaina/pgsync#462]
PGSync version: 

Postgres version: 

Elasticsearch version: 

Redis version: 

Python version: 

Problem Description: 

Error Message (if any): 

```
Hello how exactly do you get the localhost:8000 to work?
Do we need to add a container in docker compose?

```

**Comment by lisawebcoder** [comment]
hello does anyone here answer ? just wanted to know thxz LISA

**Comment by lisawebcoder** [comment]
Hello does anyone actually respond to the questions posted here?

**Comment by toluaina** [comment]
Hi, Sorry about the late response. Elasticsearch runs on default port 9300 and not 8000.
If you want to run on a different port you will need to modify the [docker-compose](https://github.com/toluaina/pgsync/blob/main/docker-compose.yml#L19) to and map 9301 to 8000

**Comment by lisawebcoder** [comment]
Hello thank you for the reply
No i am talking about your demo folder
It has the index html and runserver.sh file it runs at port 8000 but it doesn't work

Pretty sure we have to add to compose file?
But whats is exactly the configuration

**Comment by toluaina** [comment]
Good question. That runs in under virtualenv and not docker. 
You can create a virtual env 
and simply run:

- `cd demo`
-` pip install requirements.txt `
- `./runserver.sh`

**Comment by lisawebcoder** [comment]
hello i keep getting this error when i run req.txt--
Building wheels for collected packages: cchardet
  Building wheel for cchardet (pyproject.toml): started
  Building wheel for cchardet (pyproject.toml): still running...
  Building wheel for cchardet (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  Building wheel for cchardet (pyproject.toml) did not run successfully.
  exit code: 1

  [22 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-311
  creating build\lib.win-amd64-cpython-311\cchardet
  copying src\cchardet\version.py -> build\lib.win-amd64-cpython-311\cchardet
  copying src\cchardet\__init__.py -> build\lib.win-amd64-cpython-311\cchardet
  running build_ext
  building 'cchardet._cchardet' extension
  creating build\temp.win-amd64-cpython-311
  creating build\temp.win-amd64-cpython-311\Release
  creating build\temp.win-amd64-cpython-311\Release\src
  creating build\temp.win-amd64-cpython-311\Release\src\cchardet
  creating build\temp.win-amd64-cpython-311\Release\src\ext
  creating build\temp.win-amd64-cpython-311\Release\src\ext\uchardet
  creating build\temp.win-amd64-cpython-311\Release\src\ext\uchardet\src
  creating build\temp.win-amd64-cpython-311\Release\src\ext\uchardet\src\LangModels
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Isrc/ext/uchardet/src -IC:\Users\Main\desktop\internship\roberto_sync_july\demo\venv\include -IC:\Users\Main\AppData\Local\Programs\Python\Python3\include -IC:\Users\Main\AppData\Local\Programs\Python\Python3\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /EHsc /Tpsrc/cchardet\_cchardet.cpp /Fobuild\temp.win-amd64-cpython-311\Release\src/cchardet\_cchardet.obj
  _cchardet.cpp
  src/cchardet\_cchardet.cpp(196): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cchardet
Failed to build cchardet
ERROR: Could not build wheels for cchardet, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
(venv)
Main@Main-PC MINGW64 ~/desktop/internship/roberto_sync_july/demo (roberto_sync_postgres_elasticsearch_V1)
--i tried installing the  vsudio libs c++ deskop env and this is my req txt --# Demo
aiohttp
aiodns
aiohttp_cors
aiohttp-devtools
environs
cchardet--but still fet erros -- ok thxz

**Comment by lisawebcoder** [comment]
helli am stil getting this error in spite i have the containers running and they sync--gpt gives me confsuing suggestins so do you kno how to resolve this? ok thxz --
$ ./runserver.sh
Traceback (most recent call last):
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Roberto\Desktop\4thSemester\InterShip\PostInternship\July2023\june29th2023\pgsync-mainJune29th23at10amWORKS\pgsync-main\demo\venv\Scripts\adev.exe\__main__.py", line 7, in <module>
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\aiohttp_devtools\cli.py", line 99, in runserver
    run_app(**_runserver(**active_config))
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\aiohttp_devtools\runserver\main.py", line 40, in runserver
    config.import_app_factory()
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\aiohttp_devtools\runserver\config.py", line 140, in import_app_factory
    module = import_module(module_path)
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Roberto\Desktop\4thSemester\InterShip\PostInternship\July2023\june29th2023\pgsync-mainJune29th23at10amWORKS\pgsync-main\demo\server.py", line 3, in <module>
    from app.main import create_app
  File "C:\Users\Roberto\Desktop\4thSemester\InterShip\PostInternship\July2023\june29th2023\pgsync-mainJune29th23at10amWORKS\pgsync-main\demo\app\main.py", line 4, in <module>
    from app import settings
  File "C:\Users\Roberto\Desktop\4thSemester\InterShip\PostInternship\July2023\june29th2023\pgsync-mainJune29th23at10amWORKS\pgsync-main\demo\app\settings.py", line 10, in <module>
    ELASTICSEARCH_URL = env.str("ELASTICSEARCH_URL")
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\environs\__init__.py", line 116, in method
    raise EnvError('Environment variable "{}" not set'.format(proxied_key or parsed_key))
environs.EnvError: Environment variable "ELASTICSEARCH_URL" not set

**Comment by toluaina** [comment]
You need to set ELASTICSEARCH_URL in your env
e.g `export ELASTICSEARCH_URL=localhost:9300`

**Comment by lisawebcoder** [comment]
hello w/ gpt i tried set or setx and i wasnt trying expost but i tried exposrt and it shows he port but now i have a new error--
environs.EnvError: Environment variable "ELASTICSEARCH_INDEX" not set

**Comment by lisawebcoder** [comment]
$ ./runserver.sh
Traceback (most recent call last):
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Roberto\Desktop\4thSemester\InterShip\PostInternship\July2023\june29th2023\pgsync-mainJune29th23at10amWORKS\pgsync-main\demo\venv\Scripts\adev.exe\__main__.py", line 7, in <module>
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\aiohttp_devtools\cli.py", line 99, in runserver
    run_app(**_runserver(**active_config))
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\aiohttp_devtools\runserver\main.py", line 40, in runserver
    config.import_app_factory()
  File "C:\Users\Roberto\desktop\4thsemester\intership\postinternship\july2023\june29th2023\pgsync-mainjune29th23at10amworks\pgsync-main\demo\venv\lib\site-packages\aiohttp_devtools\runserver\config.py", line 140, in import_app_factory
    module = import_module(module_path)
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Roberto\Desktop\4thSemester\InterShip\PostInternship\July2023\june29th2023\pgsync-mainJune29th23at10amWORKS\pgsync-main\demo\server.py", line 3, in <module>
    from app.main import create_app
  File "C:\Users\Roberto\Desktop\4thSemester\InterShip\PostInternship\July2023\june29th2023\pgsync-mainJune29th23at10amWORKS\pgsync-main\demo\app\main.py", line 5, in <module>
    from app.views import TypeAheadView
  File "C:\Users\Roberto\Desktop\4thSemester\InterShip\PostInternship\July2023\june29th2023\pgsync-mainJune29th23at10amWORKS\pgsync-main\demo\app\views.py", line 12, in <module>
    from elasticsearch import Elasticsearch
ModuleNotFoundError: No module named 'elasticsearch'
(venv)
--hello i set the ur;l and the index but i now have the above error--i will try to ask gpt unles you know --ok thxz--

**Comment by toluaina** [comment]
Sorry about that. That demoe seems to be missing a few things. can you also install the 
pip install elasticsearch==7.13.4

**Comment by lisawebcoder** [comment]
hello yes gpt had me install these but i still dont get the index.html page and this what gpt told me but not sure i get it--
I apologize for the confusion. Let's try to narrow down the issue and go through specific steps to troubleshoot it:

1. Ensure that the `index.html` file is named correctly and placed in the same directory as the `runserver.sh` script.

2. Double-check that the content of `index.html` contains the expected search box and is correctly formatted.

3. Confirm that the server is properly configured to serve static files, including the `index.html` file.

To verify the server configuration, we need to inspect the application code and the server configuration files. Specifically, we should look for:

- How static files are served in the application (e.g., using a specific URL prefix like `/static/`, or if there's a designated endpoint to serve static files).
- The route or view function that handles requests for `/` and responds with the content of `index.html`.
- The settings or configurations related to static files and template rendering.

Since I don't have access to your application's code and configuration files, I can only provide general guidance. Please follow these steps:

1. Check the application's codebase for the route or view function that handles the root URL `/`. Make sure it returns the `index.html` file.

2. Ensure that the application's web server or framework is configured to serve static files from the appropriate directory (usually named `static` or `public`).

3. If you are using a specific framework, consult its documentation on how to properly serve static files and handle routes.

4. Verify that the server is running on the correct port. If you are using a custom port, make sure to access the application using the correct port number in the URL.

If you encounter specific error messages or logs related to the `index.html` file or the server's configuration, please share them so that I can provide more targeted assistance.

Again, I apologize for any confusion, and I'm here to help you resolve the issue step by step.

**Comment by lisawebcoder** [comment]
hello also i want  to mention in the examples/runserver.sh file i chamged the cd ./demo to cd  ../demo cuz they ar eno in the same dir
could this be why i get only a [] in the port 8000/ but i dont htink so gpt said its corect cd ../ but anyway not sure why i dont get the search box at port 8000just a an empty arry sigh []

**Comment by lisawebcoder** [comment]
Hello my container don't build anymore
I did compose and i get marshmallows error 
So i dont getvwhy i cant even run my container now

**Comment by lisawebcoder** [comment]
+] Building 43.4s (10/15)
 => [internal] load build definition from Dockerfile                                                               5.1s
 => => transferring dockerfile: 32B                                                                                0.1s
 => [internal] load .dockerignore                                                                                  2.7s
 => => transferring context: 35B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/python:3.7                                                      2.7s
 => [auth] library/python:pull token for registry-1.docker.io                                                      0.0s
 => [internal] load build context                                                                                  1.7s
 => => transferring context: 7.99kB                                                                                0.8s
 => [ 1/10] FROM docker.io/library/python:3.7@sha256:5362766ecaf46aee86aa9a6d9a3d23f7019dc2e5449ce1a97866c4ae0059  0.0s
 => CACHED [ 2/10] RUN mkdir /code                                                                                 0.0s
 => CACHED [ 3/10] ADD ./examples/ /code/examples                                                                  0.0s
 => CACHED [ 4/10] WORKDIR /code                                                                                   0.0s
 => ERROR [ 5/10] RUN pip install git+https://github.com/toluaina/pgsync.git                                      32.5s
------
 > [ 5/10] RUN pip install git+https://github.com/toluaina/pgsync.git:
#0 14.72 Collecting git+https://github.com/toluaina/pgsync.git
#0 14.72   Cloning https://github.com/toluaina/pgsync.git to /tmp/pip-req-build-4ee0nify
#0 14.79   Running command git clone --filter=blob:none --quiet https://github.com/toluaina/pgsync.git /tmp/pip-req-build-4ee0nify
#0 18.18   Resolved https://github.com/toluaina/pgsync.git to commit 0c58a657a15f989df87dbdff027e03b7c4c5b202
#0 18.20   Installing build dependencies: started
#0 24.92   Installing build dependencies: finished with status 'done'
#0 24.92   Getting requirements to build wheel: started
#0 25.21   Getting requirements to build wheel: finished with status 'done'
#0 25.22   Installing backend dependencies: started
#0 27.04   Installing backend dependencies: finished with status 'done'
#0 27.05   Preparing metadata (pyproject.toml): started
#0 28.04   Preparing metadata (pyproject.toml): finished with status 'done'
#0 28.46 Collecting opensearch-py==2.2.0
#0 28.64   Downloading opensearch_py-2.2.0-py2.py3-none-any.whl (291 kB)
#0 28.93      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 291.0/291.0 kB 1.0 MB/s eta 0:00:00
#0 29.26 Collecting certifi==2023.5.7
#0 29.29   Downloading certifi-2023.5.7-py3-none-any.whl (156 kB)
#0 29.46      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.0/157.0 kB 963.3 kB/s eta 0:00:00
#0 29.83 Collecting isort==5.11.5
#0 29.87   Downloading isort-5.11.5-py3-none-any.whl (104 kB)
#0 30.09      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 kB 447.3 kB/s eta 0:00:00
#0 30.43 ERROR: Ignored the following versions that require a different python version: 3.20.0 Requires-Python >=3.8; 3.20.1 Requires-Python >=3.8; 5.12.0 Requires-Python >=3.8.0
#0 30.43 ERROR: Could not find a version that satisfies the requirement marshmallow==3.20.1 (from pgsync) (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.7.0, 1.0.0a0, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 2.0.0a1, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0b5, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.6.0, 2.6.1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.4, 2.10.5, 2.11.0, 2.11.1, 2.12.0, 2.12.1, 2.12.2, 2.13.0, 2.13.1, 2.13.2, 2.13.3, 2.13.4, 2.13.5, 2.13.6, 2.14.0, 2.15.0, 2.15.1, 2.15.2, 2.15.3, 2.15.4, 2.15.5, 2.15.6, 2.16.0, 2.16.1, 2.16.2, 2.16.3, 2.17.0, 2.18.0, 2.18.1, 2.19.0, 2.19.1, 2.19.2, 2.19.3, 2.19.4, 2.19.5, 2.20.0, 2.20.1, 2.20.2, 2.20.3, 2.20.4, 2.20.5, 2.21.0, 3.0.0a1, 3.0.0b1, 3.0.0b2, 3.0.0b3, 3.0.0b4, 3.0.0b5, 3.0.0b6, 3.0.0b7, 3.0.0b8, 3.0.0b9, 3.0.0b10, 3.0.0b11, 3.0.0b12, 3.0.0b13, 3.0.0b14, 3.0.0b15, 3.0.0b16, 3.0.0b17, 3.0.0b18, 3.0.0b19, 3.0.0b20, 3.0.0rc1, 3.0.0rc2, 3.0.0rc3, 3.0.0rc4, 3.0.0rc5, 3.0.0rc6, 3.0.0rc7, 3.0.0rc8, 3.0.0rc9, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.2.2, 3.3.0, 3.4.0, 3.5.0, 3.5.1, 3.5.2, 3.6.0, 3.6.1, 3.7.0, 3.7.1, 3.8.0, 3.9.0, 3.9.1, 3.10.0, 3.11.0, 3.11.1, 3.12.0, 3.12.1, 3.12.2, 3.13.0, 3.14.0, 3.14.1, 3.15.0, 3.16.0, 3.17.0, 3.17.1, 3.18.0, 3.19.0)
#0 30.43 ERROR: No matching distribution found for marshmallow==3.20.1
#0 30.44
#0 30.44 [notice] A new release of pip is available: 23.0.1 -> 23.2.1
#0 30.44 [notice] To update, run: pip install --upgrade pip
------
failed to solve: executor failed running [/bin/sh -c pip install git+https://github.com/toluaina/pgsync.git]: exit code: 1

C:\Users\Roberto\Desktop\4thSemester\InterShip\PostInternship\July2023\june29th2023\pgsync-mainJune29th23at10amWORKS\pgsync-main>--after removing all aimages containers and volumes i still have this error --

**Comment by lisawebcoder** [comment]
http://localhost:8000/?q=facilityDiscountID:00b90095-edb4-47c6-98d8-24bd99e6-> [ ]---{{datasyncES}}/csdatabase/_search?q=facilityDiscountID:00b90095-edb4-47c6-98d8-24bd99e6-> rerturns data api

The browser url return empty array but api endpoints has elastic search data 
Not sure what is the issue but i still dont have index html return

**Comment by lisawebcoder** [comment]
Hello if you are able to solve it kindly let me know 
Thank you

**Comment by toluaina** [comment]
Were you able to get the demo example data working or is this your own custom dataset?
You could have run the server with ./runserver
You need to open the actual index.html on the filesystem e.g `file:///Users/USER/pgsync/demo/index.html`
I admit the demo need a bit more work to make it one click and run

**Comment by lisawebcoder** [comment]
hello yes the sync works for any dataset i chose in the examples folder and yes i created a custom dataset in the examples folder and it works for sync and its what  i was trying to access in the front end--i did  do ./runserver but i just get an empty array symbol [ ] -- i could try your airbnb dataset --but i will try to open the index html to the path you said but i not sure i get what you mean for that --ok thxz--

**Comment by lisawebcoder** [comment]
Hello if you mean access index html by by the file path in the browser when the docker container Docker containers actually are all running then yes I have I have tried that also and all it says is so I go to localhost 8000 or I go to the file path index HTML right I open it directly in the browser with the file path in my my C drive and I still get like a page cannot be loaded or you know something like

**Comment by lisawebcoder** [comment]
hello i have the docker containers running and they sync in  postman for api endpoints between elastic and postgres and i have the python server running at port 8000 and i open index html directly in my browser and i made a query iht eserach box and this is my eroor

ailed to load resource: the server responded with a status of 500 (Internal Server Error)
index.html:1 Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position 4
localhost:8000/?q=Su:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.html:1 Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position 4
localhost:8000/?q=Surr:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.html:1 Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position 4
localhost/:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
VM12:1 Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position 4
localhost/:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
VM13:1 Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position 4

**Comment by lisawebcoder** [comment]
---in the network tab i see it tried many ngrams of the word i put Surrey(its in my city table and name column) --like sur or surr or surre or surr or surrey and i get the same error so do i need to change the query liek the api endpoint ?


Request URL:
http://localhost:8000/?q=Su
Request Method:
GET
Status Code:
500 Internal Server Error
Remote Address:
127.0.0.1:8000
Referrer Policy:
strict-origin-when-cross-origin
Access-Control-Allow-Credentials:
true
Access-Control-Allow-Origin:
null
Access-Control-Expose-Headers:
Content-Length,Date,Server,Connection
Connection:
close
Content-Length:
8487
Content-Type:
text/plain; charset=utf-8
Date:
Tue, 01 Aug 2023 10:37:27 GMT
Server:
Python/3.9 aiohttp/3.8.5
Accept:
*/*
Accept-Encoding:
gzip, deflate, br
Accept-Language:
en-US,en;q=0.9
Connection:
keep-alive
Host:
localhost:8000
Origin:
null
Sec-Ch-Ua:
"Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"Windows"
Sec-Fetch-Dest:
empty
Sec-Fetch-Mode:
cors
Sec-Fetch-Site:
cross-site
User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
New CSS subgrid badge
Enable the subgrid badge to inspect and debug nested grid in the Elements panel.
Ignore content scripts by default
The debugger will automatically ignore content scripts injected by extensions.
Shortcut to set conditional breakpoints
Set a conditional breakpoint quicker using the Control / Command + click keyboard shortcut in the Sources panel.

**Comment by lisawebcoder** [comment]
Hello i have not been able to make it work
If you succeed to get it to work kindly update
Thank you
