### ISSUE TITLE
One-To-Many Update or Insert AttributeError

### ISSUE THREAD

**Issue by alameddinc** [toluaina/pgsync#49]
When I try to update or insert new row to one-to-many table, I saw error and updates doesnt show on elastic. 

When I run bootstrap again before pgsync, I didnt show any error message and complete sync successfully but This case doesnt best practice because I want to use pgsync with deamon mode.

Could you please help me :)

My Schema: 
```
[
{
  "database": "postgres",
  "index": "public",
  "nodes": [
    {
      "table": "assets",
      "schema": "public",
      "columns": [
        "title",
        "description"
      ],
      "children": [
        {
          "table": "asset_keywords",
          "schema": "public",
          "columns": [
            "keyword_keyw"
          ],
          "relationship": {
            "variant": "object",
            "type": "one_to_many"
          },
          "transform": {
            "rename": {
              "keyword_keyw": "keyword"
            }
          }
        },
        {
          "table": "asset_types",
          "schema": "public",
          "columns": [
            "title"
          ],
          "transform": {
            "rename": {
              "title": "assetType"
            }
          },
          "relationship": {
            "variant": "object",
            "type": "one_to_one"
          }
        },
        {
          "table": "visual_types",
          "schema": "public",
          "columns": [
            "title"
          ],
          "transform": {
            "rename": {
              "title": "categoryName"
            }
          },
          "relationship": {
            "variant": "object",
            "type": "one_to_one"
          }
        },
        {
          "table": "users",
          "schema": "public",
          "columns": [
            "username"
          ],
          "relationship": {
            "variant": "scalar",
            "type": "one_to_one"
          }
        }
      ]
    }
  ]
}
]
```

Error Message: 

```
2020-10-27 10:35:33.473:ERROR:pgsync.sync: Exception keyword_keyw
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/_collections.py", line 210, in __getattr__
    return self._data[key]
KeyError: 'keyword_keyw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pgsync/sync.py", line 622, in pgsync.sync.Sync._sync
  File "pgsync/query_builder.py", line 789, in pgsync.query_builder.QueryBuilder.build_queries
  File "pgsync/query_builder.py", line 271, in pgsync.query_builder.QueryBuilder._children
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: keyword_keyw
2020-10-27 10:35:33.480:ERROR:pgsync.sync: Exception: keyword_keyw
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/_collections.py", line 210, in __getattr__
    return self._data[key]
KeyError: 'keyword_keyw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pgsync/sync.py", line 691, in pgsync.sync.Sync.sync_payloads
  File "pgsync/elastichelper.py", line 56, in pgsync.elastichelper.ElasticHelper.bulk
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/helpers/actions.py", line 431, in parallel_bulk
    for result in pool.imap(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/helpers/actions.py", line 141, in _chunk_actions
    for action, data in actions:
  File "pgsync/sync.py", line 625, in _sync
  File "pgsync/sync.py", line 622, in pgsync.sync.Sync._sync
  File "pgsync/query_builder.py", line 789, in pgsync.query_builder.QueryBuilder.build_queries
  File "pgsync/query_builder.py", line 271, in pgsync.query_builder.QueryBuilder._children
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: keyword_keyw
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/_collections.py", line 210, in __getattr__
    return self._data[key]
KeyError: 'keyword_keyw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "pgsync/sync.py", line 724, in pgsync.sync.Sync.poll_redis
  File "pgsync/sync.py", line 791, in pgsync.sync.Sync.on_publish
  File "pgsync/sync.py", line 697, in pgsync.sync.Sync.sync_payloads
  File "pgsync/sync.py", line 691, in pgsync.sync.Sync.sync_payloads
  File "pgsync/elastichelper.py", line 56, in pgsync.elastichelper.ElasticHelper.bulk
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/helpers/actions.py", line 431, in parallel_bulk
    for result in pool.imap(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/helpers/actions.py", line 141, in _chunk_actions
    for action, data in actions:
  File "pgsync/sync.py", line 625, in _sync
  File "pgsync/sync.py", line 622, in pgsync.sync.Sync._sync
  File "pgsync/query_builder.py", line 789, in pgsync.query_builder.QueryBuilder.build_queries
  File "pgsync/query_builder.py", line 271, in pgsync.query_builder.QueryBuilder._children
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: keyword_keyw
Polling db postgres: 1 cache items 
```

When I tried this schema, I saw same error message. I think Its not about pivot table using or not. I think redis can not cache one to many table
```
[
{
  "database": "postgres",
  "index": "public",
  "nodes": [
    {
      "table": "assets",
      "schema": "public",
      "columns": [
        "title",
        "description"
      ],
      "children": [
        {
          "table": "keywords",
          "schema": "public",
          "columns": [
            "keyw"
          ],
          "label": "keyword",
          "relationship": {
            "variant": "scalar",
            "type": "one_to_many"
          }
        },
        {
          "table": "asset_types",
          "schema": "public",
          "columns": [
            "title"
          ],
          "transform": {
            "rename": {
              "title": "assetType"
            }
          },
          "relationship": {
            "variant": "object",
            "type": "one_to_one"
          }
        },
        {
          "table": "visual_types",
          "schema": "public",
          "columns": [
            "title"
          ],
          "transform": {
            "rename": {
              "title": "categoryName"
            }
          },
          "relationship": {
            "variant": "object",
            "type": "one_to_one"
          }
        },
        {
          "table": "users",
          "schema": "public",
          "columns": [
            "username"
          ],
          "relationship": {
            "variant": "scalar",
            "type": "one_to_one"
          }
        }
      ]
    }
  ]
}
]
```

**Comment by toluaina** [comment]
Sure, can you possibly share your db schema?
Also what version of pgsync are yous using

**Comment by toluaina** [comment]
Just looking at your first and second schema.json. Are you sure you don't have a proxy table between **assets** and **keywords**? If so, this needs to be defined in your relationship

**Comment by alameddinc** [comment]
Im sure, Because Its works correctly when I stop pgsync and restart. But If I try to run deamon mod and I inserted row to keywords when running pgsync -d ... I see error.

**Comment by toluaina** [comment]
ok I see. are you able to share your database schema dump? If not I can try to reverse from the JSON schema.  @alameddinc

**Comment by alameddinc** [comment]
![asset_keywords](https://user-images.githubusercontent.com/13180379/97405591-f96c7700-1908-11eb-8a5c-89cf0ada2035.png)

**Comment by alameddinc** [comment]
<img width="956" alt="asset_keywords" src="https://user-images.githubusercontent.com/13180379/97405720-2c166f80-1909-11eb-8abc-9b156becc671.png">

**Comment by toluaina** [comment]
Could it be that your JSON Schema is referencing. `keyword_keyw` instead of `keyword_key`?
There is no field named `keyword_keyw` according to your database schema.
@alameddinc

**Comment by alameddinc** [comment]
Hi @toluaina ,
Im sorry for this, I updated tables for new features after then open issue.I know this change but  I try again with keyword_keyw and keyword_key. I saw again. I will test with new schema on saturday.

**Comment by toluaina** [comment]
Closing as this has already be answered. Feel free to reopen if you need to
