### ISSUE TITLE
old pgsync ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by fairworlds** [toluaina/pgsync#525]
PGSync version: 
2.3.1

Postgres version: 
16.1.0
Elasticsearch/OpenSearch version: 
7.2.0
Redis version: 
7.2.4 
Python version: 
3.7
Problem Description: 

Nedd help :)

Error Message (if any): 

```
│ Traceback (most recent call last):                                                                                      │
│   File "/usr/local/bin/bootstrap", line 70, in <module>                                                                 │
│     main()                                                                                                              │
│   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__                                   │
│     return self.main(*args, **kwargs)                                                                                   │
│   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main                                       │
│     rv = self.invoke(ctx)                                                                                               │
│   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke                                     │
│     return ctx.invoke(self.callback, **ctx.params)                                                                      │
│   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke                                      │
│     return __callback(*args, **kwargs)                                                                                  │
│   File "/usr/local/bin/bootstrap", line 65, in main                                                                     │
│     sync.setup()                                                                                                        │
│   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 302, in setup                                      │
│     self.create_view(schema, tables, user_defined_fkey_tables)                                                          │
│   File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 484, in create_view                                │
│     self._materialized_views(schema),                                                                                   │
│   File "/usr/local/lib/python3.7/site-packages/pgsync/view.py", line 240, in create_view                                │
│     sa.text(f"{schema}.{MATERIALIZED_VIEW}")                                                                            │
│ ValueError: too many values to unpack (expected 3) 

```

**Comment by toluaina** [comment]
This was fixed in a later version. I would advice updgrading to the latest stable.
