### ISSUE TITLE
TypeError: '<' not supported between instances of 'dict' and 'str'

### ISSUE THREAD

**Issue by Bienqq** [toluaina/pgsync#57]
PGSync version: 1.1.22
Postgres version: 10.14
Elasticsearch version: 7.9.0
Redis version: 6.0.9
Python version: 3.8

Problem Description: 

I have bootstraped db schema:

![dropshipping](https://user-images.githubusercontent.com/35897213/100546544-327a6d00-3262-11eb-9952-e7e1e1e00509.png)

With following config file:

```json
[
  {
    "database": "dropshipping",
    "index": "dropshipping",
    "nodes": [
      {
        "table": "SellerProducts",
        "schema": "public",
        "columns": [
          "id",
          "name",
          "identifiers",
          "availableQuantity",
          "price",
          "url",
          "images",
          "description",
          "createdAt",
          "updatedAt"

        ],
        "children": [
          {
            "table": "Sellers",
            "columns": [
              "name",
              "createdAt",
              "updatedAt"
            ],
            "label": "Sellers",
            "relationship": {
              "variant": "object",
              "type": "one_to_many"
            }
          }
        ]
      }
    ]
  }
]
```

Then I have run pg sync with following command, and pgsync has been crashed
```bash
pgsync --config elastic-search-schema.json
```

Error Message (if any): 
```
 - SellerProducts
    - Sellers
 [=========================-------------------------] 50.5% 2020-11-29 16:32:14.995:ERROR:pgsync.sync: Exception '<' not supported between instances of 'dict' and 'str'
Traceback (most recent call last):
  File "/home/tomasz/.local/lib/python3.8/site-packages/pgsync/sync.py", line 731, in sync
    self.es.bulk(self.index, docs)
  File "/home/tomasz/.local/lib/python3.8/site-packages/pgsync/elastichelper.py", line 56, in bulk
    for _ in parallel_bulk(
  File "/home/tomasz/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 431, in parallel_bulk
    for result in pool.imap(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/home/tomasz/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 141, in _chunk_actions
    for action, data in actions:
  File "/home/tomasz/.local/lib/python3.8/site-packages/pgsync/sync.py", line 694, in _sync
    row = transform(self.__name, row, nodes[0])
  File "/home/tomasz/.local/lib/python3.8/site-packages/pgsync/utils.py", line 163, in transform
    return map_fields(row, structure)
  File "/home/tomasz/.local/lib/python3.8/site-packages/pgsync/utils.py", line 134, in map_fields
    value = sorted(value)
TypeError: '<' not supported between instances of 'dict' and 'str'
 0.0:0.0:3.648371696472168 (3.65 sec)
Traceback (most recent call last):
  File "/home/tomasz/.local/bin/pgsync", line 7, in <module>
    sync.main()
  File "/home/tomasz/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tomasz/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tomasz/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tomasz/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tomasz/.local/lib/python3.8/site-packages/pgsync/sync.py", line 1012, in main
    sync.pull()
  File "/home/tomasz/.local/lib/python3.8/site-packages/pgsync/sync.py", line 881, in pull
    self.sync(txmin=txmin, txmax=txmax)
  File "/home/tomasz/.local/lib/python3.8/site-packages/pgsync/sync.py", line 731, in sync
    self.es.bulk(self.index, docs)
  File "/home/tomasz/.local/lib/python3.8/site-packages/pgsync/elastichelper.py", line 56, in bulk
    for _ in parallel_bulk(
  File "/home/tomasz/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 431, in parallel_bulk
    for result in pool.imap(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/home/tomasz/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 141, in _chunk_actions
    for action, data in actions:
  File "/home/tomasz/.local/lib/python3.8/site-packages/pgsync/sync.py", line 694, in _sync
    row = transform(self.__name, row, nodes[0])
  File "/home/tomasz/.local/lib/python3.8/site-packages/pgsync/utils.py", line 163, in transform
    return map_fields(row, structure)
  File "/home/tomasz/.local/lib/python3.8/site-packages/pgsync/utils.py", line 134, in map_fields
    value = sorted(value)
TypeError: '<' not supported between instances of 'dict' and 'str'


```

**Comment by Bienqq** [comment]
I have noticed there is problem with sorting JSONB objects, since it can contain some structure eg.
```json
[
"1",
"2",
"3",
{"value": "4"}
]

```
In above scenario python cannot sort values and pgsync will crash

**Comment by toluaina** [comment]
looking into this

**Comment by toluaina** [comment]
So I have made some changes in master to handle this a bit better although this will not fix your issue.

The reason is that Postgres arrays allow heterogeneous types but Elasticsearch does not permit this. Elasticsearch arrays types are homogeneous.
See the specification for arrays in ES [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html)

**Comment by toluaina** [comment]
Closing as the data structure is not supported by Elasticsearch. Feel free to re-open if you have other questions
