### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by smokedsalmonbagel** [toluaina/pgsync#66]
PGSync version: 
1.1.24
Postgres version: 
9.6.18
Elasticsearch version: 

Redis version: 

Python version: 
3.7.9
Problem Description: 
When pgsync first starts everything seems fine.  I only have one table and a very simple schema which shows up in elastic search.   The postgres target is on AWS RDS.  It actually has many tables but I am only using one of them in my schema.json. After a few seconds I get a list index out of range followed by a number of 
```
Exception (psycopg2.errors.UndefinedObject) replication slot "my_table" does not exist
```
Is the error related to the warnings that occur just before? 

Error Message (if any): 

```
pgsync_1         | /usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3186: SAWarning: Did not recognize type 'citext' of column 'email'
pgsync_1         |   "Did not recognize type '%s' of column '%s'" % (attype, name)
pgsync_1         | /usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3186: SAWarning: Did not recognize type 'meta_tag' of column 'path'
pgsync_1         |   "Did not recognize type '%s' of column '%s'" % (attype, name)
pgsync_1         |  - my_table
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/bin/bootstrap", line 71, in <module>
pgsync_1         |     main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
pgsync_1         |     return callback(*args, **kwargs)
pgsync_1         |   File "/usr/local/bin/bootstrap", line 66, in main
pgsync_1         |     sync.setup()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 138, in setup
pgsync_1         |     self.teardown()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 163, in teardown
pgsync_1         |     self.drop_triggers(self.database, schema=schema, tables=tables)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 376, in drop_triggers
pgsync_1         |     schema, table = pairs[0], pairs[1]
pgsync_1         | IndexError: list index out of range
pgsync_1         |  - my_table

```

**Comment by toluaina** [comment]
Did you run the bootstrap command?
Can you run `bootstrap -c /path/to/schema.json `

Also, do you have any extensions enables? such as Timescale?

**Comment by toluaina** [comment]
On a closer look at the traceback, it seems you were running bootstrap.

A couple of questions: 
- are you using the default public schema
- Can you provide the table name(s)
- Do you have any other additional schemes?

**Comment by smokedsalmonbagel** [comment]
Thanks - Yes, I actually get the initial table / document showing up in ES so that part works.  It seems to be an issue in establishing the replication.  

- yes I am using the default schema (In postgres it is called 'public')
- I am testing with only one table in schema.json doc "amenities" but the DB has many tables (20 or so)
- There are other schemas listed in postgres.

**Comment by smokedsalmonbagel** [comment]
here is my schema.json
```
[
    {
      "database": "mydb",
      "index": "amenities",
      "nodes": [
          {
              "table": "amenities",
              "schema": "public",
              "columns": ["name","icon"]
          }
        ]
    }
]
```

**Comment by toluaina** [comment]
I am still unclear. Could you set the log level to `DEBUG`, then re-run bootstrap in a terminal and send me the output?
i.e 
`export CONSOLE_LOGGING_HANDLER_MIN_LEVEL=DEBUG`

Feel free to mask sensitive data

**Comment by smokedsalmonbagel** [comment]
Sure - here it is:
```
pgsync_1         | /usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3186: SAWarning: Did not recognize type 'ci****' of column '****'
pgsync_1         |   "Did not recognize type '%s' of column '%s'" % (attype, name)
pgsync_1         | 2021-01-28 21:15:11.340:INFO:elasticsearch: PUT http://elasticsearch:9200/amenities [status:200 request:0.556s]
pgsync_1         | 2021-01-28 21:15:11.341:DEBUG:pgsync.elastichelper: create index response {'acknowledged': True, 'shards_acknowledged': True, 'index': 'amenities'}
pgsync_1         | 2021-01-28 21:15:11.361:INFO:elasticsearch: GET http://elasticsearch:9200/amenities/_mapping [status:200 request:0.020s]
pgsync_1         | 2021-01-28 21:15:11.361:DEBUG:pgsync.elastichelper: created mapping: {'amenities': {'mappings': {}}}
pgsync_1         | 2021-01-28 21:15:11.366:INFO:elasticsearch: GET http://elasticsearch:9200/amenities/_settings [status:200 request:0.004s]
pgsync_1         | 2021-01-28 21:15:11.366:DEBUG:pgsync.elastichelper: created setting: {'amenities': {'settings': {'index': {'creation_date': '1611868510796', 'number_of_shards': '1', 'number_of_replicas': '1', 'uuid': 'FHCEKa7PTYSRkQXn96aBSA', 'version': {'created': '7090399'}, 'provided_name': 'amenities'}}}}
pgsync_1         | /usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3186: SAWarning: Did not recognize type 'meta****' of column '*****'
pgsync_1         |   "Did not recognize type '%s' of column '%s'" % (attype, name)
pgsync_1         |  - amenities
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/bin/bootstrap", line 71, in <module>
pgsync_1         |     main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
pgsync_1         |     return callback(*args, **kwargs)
pgsync_1         |   File "/usr/local/bin/bootstrap", line 66, in main
pgsync_1         |     sync.setup()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 138, in setup
pgsync_1         |     self.teardown()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 163, in teardown
pgsync_1         |     self.drop_triggers(self.database, schema=schema, tables=tables)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 376, in drop_triggers
pgsync_1         |     schema, table = pairs[0], pairs[1]
pgsync_1         | IndexError: list index out of range
pgsync_1         | 2021-01-28 21:15:15.892:INFO:pgsync.utils: Settings:
pgsync_1         | 2021-01-28 21:15:15.893:INFO:pgsync.utils: Schema    : examples/amenities/schema.json
pgsync_1         | 2021-01-28 21:15:15.893:INFO:pgsync.utils: -----------------------------------------------------------------
pgsync_1         | 2021-01-28 21:15:15.893:INFO:pgsync.utils: Postgres:
pgsync_1         | 2021-01-28 21:15:15.893:INFO:pgsync.utils: URL: postgresql://user:*****@myurl.rds.amazonaws.com:5432
pgsync_1         | 2021-01-28 21:15:15.893:INFO:pgsync.utils: Elasticsearch:
pgsync_1         | 2021-01-28 21:15:15.893:INFO:pgsync.utils: URL: http://elasticsearch:9200
pgsync_1         | 2021-01-28 21:15:15.893:INFO:pgsync.utils: Redis:
pgsync_1         | 2021-01-28 21:15:15.893:INFO:pgsync.utils: URL: redis://redis:6379/0
pgsync_1         | 2021-01-28 21:15:15.893:INFO:pgsync.utils: -----------------------------------------------------------------
pgsync_1         | 2021-01-28 21:15:15.898:DEBUG:pgsync.utils: Connecting to Elasticsearch without authentication.

```

**Comment by smokedsalmonbagel** [comment]
Here is the value `pairs` in drop_triggers() printed from the for loop:
```
pgsync_1         | ['meta_tag', 'SequelizeMeta']
pgsync_1         | ['meta_tag', 'association_type']
pgsync_1         | ['meta_tag', 'tag_association']
pgsync_1         | ['meta_tag', 'tag_tree']
pgsync_1         | ['notifications', 'updates']
pgsync_1         | ['notifications', 'pushes']
pgsync_1         | ['device_acknowledgements']
```
device_acknowledgements looks like it it only 1 item.

**Comment by toluaina** [comment]
Thanks this is very useful. Yes, all pairs should have 2 items. Can you also print the value of tables before splitting, please. This should be line 376

**Comment by smokedsalmonbagel** [comment]
Sure - I have 6 items all in the form '[postgres_schema].[table_name]'. 
The 7th item is 'device_acknowledgements' - there is only this string so this is clearly the issue.  This is the first table it lists in the 'public' schema.

What I did was put 
```
if len(pairs) == 1:
    schema, table = pairs[0], 'public'
```
right after 
```
pairs = table.split('.')
```
in create_tiggers(), drop_triggers(), enable_triggers() and disable_triggers()
...and it seems to be working!  So it seems like the schema name for the default schema is being dropped for some reason.

I will open a new issue for this, but I seem to be getting an error after a few minutes 
```
 Traceback (most recent call last):
pgsync_1         |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
pgsync_1         |     self.run()
pgsync_1         |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
pgsync_1         |     self._target(*self._args, **self._kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 816, in poll_db
pgsync_1         |     conn.poll()
pgsync_1         | psycopg2.OperationalError: SSL SYSCALL error: EOF detected
```
Looks like it might just be an issue with long queries?

btw - I am very excited about pgsync - it looks to be very promising for us.  I am planning to do some load testing for performance with our DB this week.

**Comment by toluaina** [comment]
Stepping back a bit. Can you please run this code snippet in a python shell.
I have been investigating this for a while.
It seems the tables are not reflected correctly.

In addition, is there anything unique about the **device_acknowledgements** table? 
e.g custom data types (although this shouldn't matter)
I am trying to understand why this table is not reflected correctly.

This should yield a list containing the schema and table name. I am guessing device_acknowledgements is treated differently.

```
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()
engine = sa.create_engine('postgresql://<user>:<password>@<host>:<port>/<database>')
metadata = sa.MetaData(schema='public')
metadata.reflect(engine)
print(metadata.tables.keys())
```

**Comment by smokedsalmonbagel** [comment]
No problem - we do have some custom data types. I get some warnings about them from sqlalchemy.  They in one of my snippets above.

public.device_acknowledgements has 5 columns, a primary key index and 2 foreign keys.  No triggers.

This script actually takes quite a while to run on our DB (30 seconds?).  The output of the script starts with this warning,
```
/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3186: SAWarning: Did not recognize type 'citext' of column 'email'
  "Did not recognize type '%s' of column '%s'" % (attype, name)
```
then lists all the tables in the public schema.  public.device_acknowledgements is included in the output.  
I am also seeing an error in the added trigger when inserting data in the amenities table after my quick fix.  
```
could not find array type for data type information_schema.sql_identifier
PL/pgSQL function table_notify() line 26 during statement block local variable initialization
```
So I am not sure adding 'public' really worked.

**Comment by toluaina** [comment]
Yes, I am not sure about adding **public** solved the problem entirely. Can you please send the output of the code snippet above to me directly?

**Comment by smokedsalmonbagel** [comment]
Ok - it is sent over to your hotmail address.

**Comment by smokedsalmonbagel** [comment]
Success! version 1.1.25 seems to be working.  I should have just upgraded when you pushed 1.1.25 🤦

**Comment by toluaina** [comment]
Yes please open a new issue for psycopg2.OperationalError: SSL SYSCALL error: EOF detected

**Comment by smokedsalmonbagel** [comment]
ok - I will close this one as it has been resolved in 1.1.25.

**Comment by smokedsalmonbagel** [comment]
I am reopening this issue - it seems to have started happening again when I tried a new schema.  My new schema uses 2 other tables in our DB which are connected with a single fk. 

On a new RDS instance I created those two tables (although I omitted some functions like create_uuid() we have in production).  pgsync seems to work fine in this fresh instance.  It seems as though there is still something going on with my production database schema and pgsync.
```
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/bin/bootstrap", line 71, in <module>
pgsync_1         |     main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
pgsync_1         |     return callback(*args, **kwargs)
pgsync_1         |   File "/usr/local/bin/bootstrap", line 66, in main
pgsync_1         |     sync.setup()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 140, in setup
pgsync_1         |     self.teardown()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 165, in teardown
pgsync_1         |     self.drop_triggers(self.database, schema=schema, tables=tables)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 376, in drop_triggers
pgsync_1         |     schema, table = pairs[0], pairs[1]
pgsync_1         | IndexError: list index out of range
```

**Comment by smokedsalmonbagel** [comment]
Update on this - it looks like the problem resolved itself this morning.  So there is almost certainly something about the database state that causes this error which is 'reset' after restarting.

**Comment by toluaina** [comment]
Are you able to try again on a new instance and print some logs on and around the point of failure?

**Comment by toluaina** [comment]
That was very useful. I have made some changes to resolve this on master. 
Can you try this out and let me know

**Comment by smokedsalmonbagel** [comment]
Awesome - I grabbed the new code and haven't seen the error so far.  I will be testing with a new database this week with a pretty complex schema - I will let you know how it goes.

**Comment by toluaina** [comment]
Hoping to close this for now. Re-open if you see thr need to
