### ISSUE TITLE
replication slot name %NAME Fail if contains invalid caracters

### ISSUE THREAD

**Issue by miguelrock22** [toluaina/pgsync#71]
PGSync version: 1.1.25

Postgres version: 11.8 (RDS)

Elasticsearch version: 7.5.1

Redis version: 6.0.10

Python version: 3

Problem Description: Error creating the replication slot when the database name contains dash (-) or another symbol that doesn't match whit the postgres specification (https://www.postgresql.org/docs/10/warm-standby.html#STREAMING-REPLICATION-SLOTS-MANIPULATION 26.2.6.1) ant it breaks the sync process.

Error Message (if any): 

```
wait-for-it.sh: waiting 120 seconds for redis:6379
wait-for-it.sh: redis:6379 is available after 0 seconds
2021-02-03 21:34:47.951:ERROR:pgsync.base: Exception (psycopg2.errors.InvalidName) replication slot name "pruebas-cliente_products" contains invalid character
HINT:  Replication slot names may only contain lower case letters, numbers, and the underscore character.

[SQL: SELECT *
FROM PG_CREATE_LOGICAL_REPLICATION_SLOT(%(PG_CREATE_LOGICAL_REPLICATION_SLOT_1)s, %(PG_CREATE_LOGICAL_REPLICATION_SLOT_2)s)]
[parameters: {'PG_CREATE_LOGICAL_REPLICATION_SLOT_1': 'pruebas-cliente_products', 'PG_CREATE_LOGICAL_REPLICATION_SLOT_2': 'test_decoding'}]
(Background on this error at: http://sqlalche.me/e/13/f405)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidName: replication slot name "pruebas-cliente_products" contains invalid character
HINT:  Replication slot names may only contain lower case letters, numbers, and the underscore character.

```

**Comment by toluaina** [comment]
This has now been resolved in the master branch. I will be cutting a release shortly

**Comment by toluaina** [comment]
This has now been included in the latest release
