### ISSUE TITLE
trigger "TABLE_notify" for relation "TABLE" already exists

### ISSUE THREAD

**Issue by aloysius-tim** [toluaina/pgsync#74]
**PGSync version**: Docker version
**Postgres version**: RDS PostgreSQL 10.13
**Elasticsearch version**: 7.9
**Redis version**: Docker version
**Python version**: Docker version (3.7)

**Problem Description**: 
Hey guys! Thanks for this awesome project that I'm looking forward to using in production.

My connection to POSTGRESQL and ELASTIC is successful. But I get an error on TRIGGER creation. I tried to DROP manually triggers and relaunch DEAMON but without any success... Any idea?

My RDS POSTGRESQL has been created from a SNAPSHOT of my production base.

Thanks a lot, guys

PS: **I plan to use PGSYNC on a single PG table with 10M+ rows... Is pgsync suitable for this amount of rows ?**

**Error Message (if any)**: 
```
pgsync_1  | Traceback (most recent call last):
pgsync_1  |   File "/usr/local/bin/bootstrap", line 68, in <module>
pgsync_1  |     main()
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
pgsync_1  |     return self.main(*args, **kwargs)
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
pgsync_1  |     rv = self.invoke(ctx)
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
pgsync_1  |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
pgsync_1  |     return callback(*args, **kwargs)
pgsync_1  |   File "/usr/local/bin/bootstrap", line 63, in main
pgsync_1  |     sync.setup()
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 148, in setup
pgsync_1  |     self.create_triggers(self.database, schema, tables=tables)
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 370, in create_triggers
pgsync_1  |     self.execute(query)
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 419, in execute
pgsync_1  |     conn.execute(query, values)
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
pgsync_1  |     return self._execute_text(object_, multiparams, params)
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
pgsync_1  |     parameters,
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
pgsync_1  |     e, statement, parameters, cursor, context
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
pgsync_1  |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
pgsync_1  |     raise exception
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
pgsync_1  |     cursor, statement, parameters, context
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
pgsync_1  |     cursor.execute(statement, parameters)
pgsync_1  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateObject) trigger "annonces_parsed_notify" for relation "annonces_parsed" already exists
pgsync_1  | 
pgsync_1  | [SQL: CREATE TRIGGER annonces_parsed_notify AFTER INSERT OR UPDATE OR DELETE ON "index"."annonces_parsed" FOR EACH ROW EXECUTE PROCEDURE table_notify()]
pgsync_1  | [parameters: (None,)]
pgsync_1  | (Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by toluaina** [comment]
Can you please provide details of your pgsync schema config. 

With 10M rows, the initial sync will take the longest.

**Comment by toluaina** [comment]
I just read the entire description again,  You indicated that you manually deleted the trigger.
I would suggest bootstrapping the DB all over.

> bootstrap -t -c /path/to/schema.json
> bootstrap -c /path/to/schema.json

**Comment by toluaina** [comment]
Did this work?

@aloysius-tim

**Comment by aloysius-tim** [comment]
Hello @toluaina,

Thanks a lot for your help. It looks like it's working (at least I do not get the TRIGGER error..). Now waiting for the 10M rows sync :-)

I should have checked the bootstrap options. But anyway, would be great to add some documentation about this script and inputs

Thanks again

**Comment by aloysius-tim** [comment]
No more errors about the triggers. But my Pgsync container got killed (exited with code 137) without any additional logs.

Any idea? Do you think it could be related to the SA or REDIS warnings I get?

```
➜  pgsync git:(master) docker-compose logs -f
Attaching to pgsync_pgsync_1, pgsync_redis_1
pgsync_1  | wait-for-it.sh: waiting 60 seconds for redis:6379
pgsync_1  | wait-for-it.sh: redis:6379 is available after 0 seconds
pgsync_1  | /usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3199: SAWarning: Did not recognize type 'geometry' of column 'geom'
pgsync_1  |   "Did not recognize type '%s' of column '%s'" % (attype, name)
pgsync_1  | /usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3530: SAWarning: Skipped unsupported reflection of expression-based index idx_lower_email
pgsync_1  |   "expression-based index %s" % idx_name
pgsync_1  | /usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3538: SAWarning: Predicate of partial index idx_uniq_table_db_id_schema_name_2col ignored during reflection
pgsync_1  |   % idx_name
pgsync_1  | /usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3538: SAWarning: Predicate of partial index idx_uniq_field_table_id_parent_id_name_2col ignored during reflection
pgsync_1  |   % idx_name
pgsync_1  | pg_settings:
pgsync_1  | SELECT setting
pgsync_1  | FROM pg_settings
pgsync_1  | WHERE name = 'max_replication_slots'pg_settings:
pgsync_1  | SELECT setting
pgsync_1  | FROM pg_settings
pgsync_1  | WHERE name = 'wal_level'pg_settings:
pgsync_1  | SELECT setting
pgsync_1  | FROM pg_settings
pgsync_1  | WHERE name = 'rds.logical_replication' - annonces_parsed
redis_1   | 1:C 10 Feb 2021 14:50:29.328 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1   | 1:C 10 Feb 2021 14:50:29.329 # Redis version=6.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1   | 1:C 10 Feb 2021 14:50:29.329 # Configuration loaded
redis_1   | 1:M 10 Feb 2021 14:50:29.330 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
redis_1   | 1:M 10 Feb 2021 14:50:29.330 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
redis_1   | 1:M 10 Feb 2021 14:50:29.330 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
redis_1   | 1:M 10 Feb 2021 14:50:29.331 * Running mode=standalone, port=6379.
redis_1   | 1:M 10 Feb 2021 14:50:29.331 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1   | 1:M 10 Feb 2021 14:50:29.331 # Server initialized
redis_1   | 1:M 10 Feb 2021 14:50:29.331 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1   | 1:M 10 Feb 2021 14:50:29.332 * Ready to accept connections
redis_1   | 1:C 19 Feb 2021 14:05:15.288 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1   | 1:C 19 Feb 2021 14:05:15.288 # Redis version=6.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1   | 1:C 19 Feb 2021 14:05:15.288 # Configuration loaded
redis_1   | 1:M 19 Feb 2021 14:05:15.289 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
redis_1   | 1:M 19 Feb 2021 14:05:15.289 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
redis_1   | 1:M 19 Feb 2021 14:05:15.289 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
redis_1   | 1:M 19 Feb 2021 14:05:15.291 * Running mode=standalone, port=6379.
redis_1   | 1:M 19 Feb 2021 14:05:15.291 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1   | 1:M 19 Feb 2021 14:05:15.291 # Server initialized
redis_1   | 1:M 19 Feb 2021 14:05:15.291 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1   | 1:M 19 Feb 2021 14:05:15.291 * Ready to accept connections
pgsync_1  | Killed
pgsync_pgsync_1 exited with code 137
```

**Comment by toluaina** [comment]
This is from Redis. It appears you have reached the fd limit. You would need to increase this. If you are running in docker you can add this to the docker compose file . You can do something like [this](https://stackoverflow.com/questions/40683285/max-file-descriptors-4096-for-elasticsearch-process-is-too-low-increase-to-at)

**Comment by aloysius-tim** [comment]
I've upgrated the REDIS server and monitored it: no activity at all.

I don't think it's related to the REDIS as it doesn't receive any activity ?

**Comment by aloysius-tim** [comment]
I've also tried to upgrade my PGSYNC instance and Elastic (REDIS too, but it does not get any activity at all, I doubt it is related), but still getting the same error
Do you have any idea what could be the error source?

Thanks a lot,
Tim

**Comment by toluaina** [comment]
You mentioned that your source database has millions of records. 
The OOM-Killer might be terminating the process.
I would suggest tweaking the pgsync parameters a bit. 

Perhaps try reducing

- QUERY_CHUNK_SIZE
- ELASTICSEARCH_CHUNK_SIZE
- ELASTICSEARCH_THREAD_COUNT

The defaults are documented [here](https://pgsync.com/env-vars/)

**Comment by aloysius-tim** [comment]
Thanks for your answer @toluaina 

I tried to reduce all these ENV vars, without any success. Also tried to upSize the Elastic & Redis & Pgsync server.

Do you think it could be related to the docker container running PGSYNC ?

Thanks

**Comment by tinger2** [comment]
Can you check the system logs to see /confirm why pgsync was killed? This probably triggered by the OOm killer because it is using too much memory?

Also, can you run the **_airbnb_** example on the same hosts to eliminate the possible causes?

I am guessing the current issue you are having is the pgsync process is getting killed.

**Comment by toluaina** [comment]
I think you might need to increase the **vm.max_map_count** 
Before you do can you run the airbnb example using your current configurations. 
i.e **_redis_**, **_elasticsearch_** and **_postgres_** host

**Comment by toluaina** [comment]
Closning this for now
