### ISSUE TITLE
relation "notifications.[table]" does not exist

### ISSUE THREAD

**Issue by smokedsalmonbagel** [toluaina/pgsync#76]
PGSync version: 
commit fea34a7d363c24490d3cdc95e84835c23db11cde
Postgres version: 
10.11
Elasticsearch version: 

Redis version: 

Python version: 

Problem Description: 
I have a table which can be joined to another table via 3 possible foreign keys.  It can also be joined via what is effectively a bridge entity table:
```
           registrations                  devices
         +------------------+        +-----------------+
         |                  |        |                 |
+------->+  id              |   +--->+    id           |
|        |                  |   |    |                 |
|        |  device_type1_id +---+    |    field1       |
|        |                  |   |    |                 |
|        |  device_type2_id +---+    |    field2       |
|        |                  |   |    |                 |
|        |  device_type3_id +---+    |                 |
|        |                  |   |    |                 |
|        |                  |   |    |                 |
|        +------------------+   |    +-----------------+
|                               |
|                               |
|             bridge            |
|        +------------------+   |
|        |                  |   |
|        |  id              |   |
|        |                  |   |
+--------+  reg_id          |   |
         |                  |   |
         |  device_id       +---+
         |                  |
         |                  |
         +------------------+

```
Here is my schema:
```
[
    {
      "database": "mydb",
      "index":"registrations",
      "nodes":[
          {
              "table": "registrations",
              "schema": "public",
              "columns":["some_field"],
              "children": [
                {
                    "table": "devices",
                    "columns": [
                        "field1"
                    ],
                    "relationship": {
                        "variant": "object",
                        "type": "one_to_one"
                    }
                }
              ]
          }
        ]

    }
]
```
I realize this is a bit ambiguous as to how the join occurs - is this sort of schema possible with pgsync? 

Error Message (if any): 

```

pgsync_1         | 2021-02-18 17:01:22.933:ERROR:pgsync.base: Exception (psycopg2.errors.UndefinedTable) relation "notifications.devices" does not exist
pgsync_1         | 
pgsync_1         | [SQL: CREATE TRIGGER devices_notify AFTER INSERT OR UPDATE OR DELETE ON "notifications"."devices" FOR EACH ROW EXECUTE PROCEDURE table_notify()]
pgsync_1         | [parameters: (None,)]
pgsync_1         | (Background on this error at: http://sqlalche.me/e/13/f405)
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
pgsync_1         |     cursor, statement, parameters, context
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
pgsync_1         |     cursor.execute(statement, parameters)
pgsync_1         | psycopg2.errors.UndefinedTable: relation "notifications.devices" does not exist

```

**Comment by toluaina** [comment]
I think what you need is a way of specifying the foreign key via the relationship attribute.
This feature has been requested before. It still requires a bit of RnD. I started work on it in a branch but haven't completed it yet.

**Comment by smokedsalmonbagel** [comment]
Ok - I remember seeing what you are describing in the issues.  I agree with the point that having the relationships in the DB rather than schema.json makes the most sense and is the cleanest.  But I didn't consider cases like this where the relationship  is present but ambiguous.  I like the idea of being able to supply a foreign_key in the relationship node.  Looking forward to this.

**Comment by toluaina** [comment]
Oops sorry did not realize you had a question at the end of the last post. Foreign key can now be defined in the schema. 
This is also documented [here](https://pgsync.com/tutorial/relationship-with-user-defined-foreign-key/)

**Comment by toluaina** [comment]
Closing as this Foreign Keys with no constrainsts are now supported
