### ISSUE TITLE
Transaction Log not cleaned up; also "KeyError: 'ID'"

### ISSUE THREAD

**Issue by DonHansDampf** [toluaina/pgsync#81]
PGSync version: 1.1.25

Postgres version: 9.6

Elasticsearch version: 7.10

Redis version: 5.0.3

Python version: 3.6.8

Problem Description: 

We deployed pgsync on a single PSQL host (running RHEL8.2) and are trying to sync a single table from a jira database. Our pgsync.conf looks like this:

```

  {
    "database": "jiradb",
    "index": "pgsync_jira_maillog",
    "setting": {},
    "nodes": [
      {
        "table": "AO_2C4E5C_MAILITEMAUDIT",
        "schema": "public",
        "columns": [
          "CREATED_TIMESTAMP",
          "FROM_ADDRESS",
          "HANDLER_NAME_KEY",
          "ID",
          "ISSUE_KEY",
          "MAIL_CHANNEL_ID",
          "MAIL_CHANNEL_NAME",
          "MAIL_ITEM_ID",
          "MESSAGE",
          "NO_OF_RETRY",
          "RESULT_STATUS",
          "SUBJECT",
          "UPDATED_TIMESTAMP"
        ]
      }
    ]
  }
]
```

In the beginning I encountered the Error down below while running with `--daemon`. So we created a cronjob and let it run every 10 minutes, which worked fine for a week. I had now to notice, that the pg_xlog directory isn't getting cleaned up. I red about, that pgsync doesn't clean up the wal archive while running without `--daemon`. But even letting it run with `--daemon`, doesn't help. Most of the time no error is reported, but sometimes I get the error printed out down below. The pg_xlog directory still doesn't get cleaned up.

The synced Table looks like this:

```
jiradb=# \d public."AO_2C4E5C_MAILITEMAUDIT"
                                       Table "public.AO_2C4E5C_MAILITEMAUDIT"
      Column       |          Type          |                               Modifiers
-------------------+------------------------+------------------------------------------------------------------------
 CREATED_TIMESTAMP | bigint                 | default 0
 FROM_ADDRESS      | character varying(255) |
 HANDLER_NAME_KEY  | character varying(255) |
 ID                | integer                | not null default nextval('"AO_2C4E5C_MAILITEMAUDIT_ID_seq"'::regclass)
 ISSUE_KEY         | character varying(255) |
 MAIL_CHANNEL_ID   | integer                | default 0
 MAIL_CHANNEL_NAME | character varying(255) |
 MAIL_ITEM_ID      | integer                |
 MESSAGE           | character varying(255) |
 NO_OF_RETRY       | integer                | default 0
 RESULT_STATUS     | character varying(255) |
 SUBJECT           | character varying(255) |
 UPDATED_TIMESTAMP | bigint                 | default 0
Indexes:
    "AO_2C4E5C_MAILITEMAUDIT_pkey" PRIMARY KEY, btree ("ID")
    "index_ao_2c4e5c_mai1011024424" btree ("MAIL_ITEM_ID")
Foreign-key constraints:
    "fk_ao_2c4e5c_mailitemaudit_mail_item_id" FOREIGN KEY ("MAIL_ITEM_ID") REFERENCES "AO_2C4E5C_MAILITEM"("ID")
Triggers:
    ao_2c4e5c_mailitemaudit_notify AFTER INSERT OR DELETE OR UPDATE ON "AO_2C4E5C_MAILITEMAUDIT" FOR EACH ROW EXECUTE PROCEDURE table_notify()
    ao_2c4e5c_mailitemaudit_truncate AFTER TRUNCATE ON "AO_2C4E5C_MAILITEMAUDIT" FOR EACH STATEMENT EXECUTE PROCEDURE table_notify()
```

Am I missing something or is the field `ID` (Foreign-Key) causing this problem? I wouldn't care if we could drop the ID field. 

Error Message (if any): 

```
Traceback (most recent call last):
  File "/usr/local/bin/pgsync", line 7, in <module>
    sync.main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pgsync/sync.py", line 1019, in main
    sync.pull()
  File "/usr/local/lib/python3.6/site-packages/pgsync/sync.py", line 885, in pull
    self.logical_slot_changes(txmin=txmin, txmax=txmax)
  File "/usr/local/lib/python3.6/site-packages/pgsync/sync.py", line 243, in logical_slot_changes
    self.sync_payloads(payloads)
  File "/usr/local/lib/python3.6/site-packages/pgsync/sync.py", line 745, in sync_payloads
    payloads,
  File "/usr/local/lib/python3.6/site-packages/pgsync/sync.py", line 349, in _payloads
    payload_data[key] for key in primary_keys
  File "/usr/local/lib/python3.6/site-packages/pgsync/sync.py", line 349, in <listcomp>
    payload_data[key] for key in primary_keys
KeyError: 'ID'
```

Hope you can help me out. Thank you very much!

Best regards,
Marcel

**Comment by DonHansDampf** [comment]
Hi @toluaina ,

did some more runs, and sadly got the same error after a some long execution time:

```
[xxx@xxx bin]$ python3 ./pgsync --config /etc/pgsync.conf
 - AO_2C4E5C_MAILITEMAUDIT
 [==================================================] 100.0%
 0:02:28.492516 (148.49 sec)
Traceback (most recent call last):
  File "./pgsync", line 7, in <module>
    sync.main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pgsync/sync.py", line 1017, in main
    sync.pull()
  File "/usr/local/lib/python3.6/site-packages/pgsync/sync.py", line 883, in pull
    self.logical_slot_changes(txmin=txmin, txmax=txmax)
  File "/usr/local/lib/python3.6/site-packages/pgsync/sync.py", line 249, in logical_slot_changes
    self.sync_payloads(payloads)
  File "/usr/local/lib/python3.6/site-packages/pgsync/sync.py", line 737, in sync_payloads
    payloads,
  File "/usr/local/lib/python3.6/site-packages/pgsync/sync.py", line 355, in _payloads
    payload_data[key] for key in primary_keys
  File "/usr/local/lib/python3.6/site-packages/pgsync/sync.py", line 355, in <listcomp>
    payload_data[key] for key in primary_keys
KeyError: 'ID'
```

**Comment by DonHansDampf** [comment]
> In any case, keep an eye on it and let me know if that error re-surfaces.

See my post just before yours: It seems like the error still persists. It doesn't happen every time, more like every 10th oder 15th execution.

**Comment by toluaina** [comment]
To expedite this can you please print out the value of row on [this line](https://github.com/toluaina/pgsync/blob/master/pgsync/base.py#L533) and sent the output when the error occurs

e.g 
```
print(row)
print('-' * 100)
```

**Comment by DonHansDampf** [comment]
For anybody finding this issue, on the search why pg_xlog doesn't get cleaned up:

Normally the database itself does clean up the pg_xlog directory. There are many (!) reason why it doesn't happen if something goes wrong. But one reason I encountered while using pgsync:

pgsync registeres a replication slot in the database. Postgres only cleans up the pg_xlog directory, when every replication slot "received" each transaction. If you change your pgsync.conf, and change the replication slot name, you need to rerun `bootstrap`. `bootstrap` creates this replication slot. 

I simply changed the name of the slot and never bothered to check the active slots. The unused, old slot blocked the pg_xlog cleanup.

Simply run `SELECT * FROM pg_replication_slots ;` to list the registered slots. If there is an old unused pgsync slot, it's probably inactive, and you can simply remove it by `SELECT pg_drop_replication_slot('NAMEOFSLOT');`.

Hope this helps someone!
