### ISSUE TITLE
Update data CHILDREN

### ISSUE THREAD

**Issue by martinhogf** [toluaina/pgsync#94]
PGSync version: 1.1.30

Postgres version: 12.x

Elasticsearch version: 7.10.1

Redis version: 6.0.5

Python version: 3.9.2

Problem Description: 
I am trying to use this lib to make replications to a query database (Elasticsearch). Does this lib update the data only from the PIVOT table or does it also update the Childrens data (this is not happening)?

My schema:
`
[
	{
		"database": "database",
		"index": "my_index",
		"nodes": [
			{
				"table": "tableA",
				"schema": "register",
				"columns": [
					"id",
					"name",
					"description"
				],
				"children": [
					{
                        "table": "tableB",
						"schema": "register",
                        "columns": [
                            "id",
							"description"
                        ],
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_one"
                        }
                    }
				]
			}
		]
	}
]
`

Error Message (if any): 

```


```
Thank you for lib.

**Comment by toluaina** [comment]
PGSync should update the child entities.

Did you bootstrap the database or encounter any errors when you did? 

whats happens when you run pgsync as a daemon?

`pgsync -d`

**Comment by martinhogf** [comment]
Did you bootstrap the database or encounter any errors when you did?
Indicates an error that the trigger already exists (this happens even after executing the bootstrap -t command)

whats happens when you run pgsync as a daemon?
I haven't tried to run as a daemon yet, but when running pgsync an error is displayed saying that the replication slot does not exist.

I am using an AWS RDS (I am using a superuser and I have already enabled the group parameter rds_replication_logical)

**Comment by martinhogf** [comment]
If an update only happens to the child's information, does synchronization happen? Is the child updated on all documents in Elasticsearch?

**Comment by toluaina** [comment]
> If an update only happens to the child's information, does synchronization happen? Is the child updated on all documents in Elasticsearch?

That is correct. All children will be updated in all docs.

**Comment by toluaina** [comment]
Did you get over that issue. Can you bootstrap successfully. If not can you provide the full traceback

**Comment by martinhogf** [comment]
The first problem I have is when I try to boot the database by running the bootstrap command (I'm running bootstrap -t before anything).

Below is the traceback:
`
bootstrap -v
2021-04-06 11:30:45.605:ERROR:pgsync.base: Exception (psycopg2.errors.DuplicateObject) trigger "tb_entidade_tipo_notify" for relation "tb_entidade_tipo" already exists

[SQL: CREATE TRIGGER tb_entidade_tipo_notify AFTER INSERT OR UPDATE OR DELETE ON "cadastro"."tb_entidade_tipo" FOR EACH ROW EXECUTE PROCEDURE table_notify()]
[parameters: (None,)]
(Background on this error at: http://sqlalche.me/e/13/f405)
Traceback (most recent call last):
  File "C:\users\martinho.feitoza\appdata\local\programs\python\python39\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\users\martinho.feitoza\appdata\local\programs\python\python39\lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateObject: trigger "tb_entidade_tipo_notify" for relation "tb_entidade_tipo" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\users\martinho.feitoza\appdata\local\programs\python\python39\lib\site-packages\pgsync\base.py", line 428, in execute
    conn.execute(query, values)
  File "C:\users\martinho.feitoza\appdata\local\programs\python\python39\lib\site-packages\sqlalchemy\engine\base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "C:\users\martinho.feitoza\appdata\local\programs\python\python39\lib\site-packages\sqlalchemy\engine\base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "C:\users\martinho.feitoza\appdata\local\programs\python\python39\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\users\martinho.feitoza\appdata\local\programs\python\python39\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\users\martinho.feitoza\appdata\local\programs\python\python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\users\martinho.feitoza\appdata\local\programs\python\python39\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\users\martinho.feitoza\appdata\local\programs\python\python39\lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateObject) trigger "tb_entidade_tipo_notify" for relation "tb_entidade_tipo" already exists
`

**Comment by toluaina** [comment]
I suspect the bootstrap teardown is not working as expected. I will take a look at this

**Comment by toluaina** [comment]
Can you try with the latest release? 
This should be a bit more robust and handle duplicate declarations better.
@martinhogf

**Comment by martinhogf** [comment]
First of all congratulations on the library. It worked perfectly after upgrading to the new release.

I would like to thank you for your willingness to help and for the quick solution. It really does make a difference.

Then I would like to know how to be able to contribute in some way to the evolution of this library.

Cheers!

**Comment by toluaina** [comment]
Thanks. This is good to know. Feel free to contribute by submitting a PR for improvements or features.

**Comment by martinhogf** [comment]
Thank you!
