### ISSUE TITLE
if _id is specified it must not be empty

### ISSUE THREAD

**Issue by dgastudio** [toluaina/pgsync#97]
PGSync version: 
:latest
Postgres version: 
:latest
Elasticsearch version: 
:latest
Redis version: 
:latest
Python version: 
:latest
Problem Description: 

if _id is specified it must not be empty

Table structure:
https://monosnap.com/file/GCknHgeJiByqtkmP5T7IYU4QoE68ZP

schema.json
https://monosnap.com/file/ns2Wuv0zD9Rj7fRvEFGmDMRzUa7dhU

Full error 
{
   "index":{
      "_index":"elastic_bundle",
      "_type":"_doc",
      "_id":"",
      "status":400,
      "error":{
         "type":"illegal_argument_exception",
         "reason":"if _id is specified it must not be empty"
      },
      "data":{
         "id":61,
         "machine_name":"unit_other",
         "entity_type":"unit",
         "_meta":{
            
         }
      }
   }
}
]

i have tried to rename id to _id in my fields list, but no result.

can you please, give me an advice about what is wrong? thank you!

**Comment by toluaina** [comment]
That's odd. Is that the full traceback? You should be able to add `id` field withouth renaming it to something else. 

Did the error occur when you tried to rename it?
If so can you send me the pgsync config of your rename transformation?

**Comment by dgastudio** [comment]
Hello and thank you for your response.
Step by step

-----------

schema.json
[
  {
    "database": "hk_dev",
    "index": "elastic_bundle",
    "nodes": [
      {
        "table": "eck_bundle",
        "columns": [
          "id",
          "machine_name",
          "entity_type"
        ]
      }
    ]
  }
]

-----------

bootstrap --config schema.json

/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/base.py:4137: SAWarning: Skipped unsupported reflection of expression-based index menu_links_path_menu_idx
  util.warn(
/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/base.py:4137: SAWarning: Skipped unsupported reflection of expression-based index menu_links_router_path_idx
  util.warn(
/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/base.py:4137: SAWarning: Skipped unsupported reflection of expression-based index menu_router_tab_parent_idx
  util.warn(
/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/base.py:4137: SAWarning: Skipped unsupported reflection of expression-based index menu_router_tab_root_weight_title_idx
  util.warn(
/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/base.py:4137: SAWarning: Skipped unsupported reflection of expression-based index node_node_title_type_idx
  util.warn(
/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/base.py:4137: SAWarning: Skipped unsupported reflection of expression-based index node_node_type_idx
  util.warn(
 - eck_bundle

-----------

pgsync --config schema.json

very long output, but the most basically repeats the same for each row
https://pastebin.com/ih23nSfR

thank you

**Comment by toluaina** [comment]
For some reason, your root table has no primary keys or is not being reflected. 
I'm unable to see your db schema to know why

Do you have any primary keys defined in "eck_bundle"? if so what are they?Do you have any primary keys defined in "eck_bundle" ? if so whatr are they?

**Comment by dgastudio** [comment]
https://monosnap.com/file/Gt1F8EWqPN3Clitv3NO3Pr0GaSw5UR

DROP TABLE IF EXISTS "public"."eck_bundle";

-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS eck_bundle_id_seq;

-- Table Definition
CREATE TABLE "public"."eck_bundle" (
    "id" int4 NOT NULL DEFAULT nextval('eck_bundle_id_seq'::regclass) CHECK (id >= 0),
    "machine_name" varchar(128) NOT NULL,
    "entity_type" varchar(128) NOT NULL,
    "name" varchar(128) NOT NULL,
    "label" varchar(128) NOT NULL,
    "config" text NOT NULL,
    PRIMARY KEY ("id")
);

-- Column Comment
COMMENT ON COLUMN "public"."eck_bundle"."id" IS 'The primary identifier for a bundle';
COMMENT ON COLUMN "public"."eck_bundle"."machine_name" IS 'A combination of the entity type and the name ofthis bundle, this combination is unique';
COMMENT ON COLUMN "public"."eck_bundle"."entity_type" IS 'The entity type this bundle belongs to';
COMMENT ON COLUMN "public"."eck_bundle"."name" IS 'The bundle''s name';
COMMENT ON COLUMN "public"."eck_bundle"."label" IS 'A human readable name for the bundle (not that the type is not human readable)';
COMMENT ON COLUMN "public"."eck_bundle"."config" IS 'A serialized list of the bundle settings.';

-- Table Comment
COMMENT ON TABLE "public"."eck_bundle" IS 'The base table for bundle information';

**Comment by toluaina** [comment]
Would you mind running the sync in verbose `-v`  and sending the output  please. 
Perhaps send me the log directly.

**Comment by toluaina** [comment]
Can you also please provide the version of 

- PGSync
- Postgres
- Elasticsearch
- Redis
- Python

**Comment by lokesh-everest** [comment]
I'm facing same issue with one of the table. Rest of the tables its working fine. For this table its nor working. Not sure what's the problem. 

`pg_settings:
SELECT setting
FROM pg_settings
WHERE name = %(name_1)spg_settings:
SELECT setting
FROM pg_settings
WHERE name = %(name_1)spg_settings:
SELECT setting
FROM pg_settings
WHERE name = %(name_1)shas_permission:
SELECT usesuper
FROM pg_user
WHERE usename = %(usename_1)s
  AND usesuper = TRUEreplication_slots:
SELECT *
FROM PG_REPLICATION_SLOTS
WHERE slot_name = %(slot_name_1)s
  AND slot_type = %(slot_type_1)s
  AND plugin = %(plugin_1)s - companies
txid_current:
SELECT *
FROM TXID_CURRENT()Query:
SELECT JSON_BUILD_ARRAY() AS "JSON_BUILD_ARRAY_1",
       JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_2)s, companies_1.id, %(JSON_BUILD_OBJECT_3)s, companies_1.name, %(JSON_BUILD_OBJECT_4)s, companies_1.website) AS "JSON_BUILD_OBJECT_1"
FROM public.companies AS companies_1
WHERE CAST(CAST(companies_1.xmin AS TEXT) AS BIGINT) < %(param_1)s1)
Pkeys: []
{'_meta': {},
 'id': '11c716f2-48ee-44fc-a7a4-c3398e286ae8',
 'name': 'Test company',
 'website': 'test.com'}
----------
2)
Pkeys: []
{'_meta': {},
 'id': '1e0c0b21-0386-439a-9639-68e5e5f4d228',
 'name': 'Everest engineering',
 'website': 'everest.engineering'}
----------
2021-06-15 16:51:33.245:ERROR:pgsync.sync: Exception ('2 document(s) failed to index.', [{'index': {'_index': 'companies_index', '_type': '_doc', '_id': '', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'if _id is specified it must not be empty'}, 'data': {'id': '11c716f2-48ee-44fc-a7a4-c3398e286ae8', 'name': 'Test company', 'website': 'test.com', '_meta': {}}}}, {'index': {'_index': 'companies_index', '_type': '_doc', '_id': '', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'if _id is specified it must not be empty'}, 'data': {'id': '1e0c0b21-0386-439a-9639-68e5e5f4d228', 'name': 'Everest engineering', 'website': 'everest.engineering', '_meta': {}}}}])
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pgsync/sync.py", line 826, in sync
    self.es.bulk(self.index, docs)
  File "/usr/local/lib/python3.9/site-packages/pgsync/elastichelper.py", line 82, in bulk
    for _ in parallel_bulk(
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/helpers/actions.py", line 454, in parallel_bulk
    for result in pool.imap(
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/helpers/actions.py", line 455, in <lambda>
    lambda bulk_chunk: list(
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/helpers/actions.py", line 246, in _process_bulk_chunk
    for item in gen:
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/helpers/actions.py", line 185, in _process_bulk_chunk_success
    raise BulkIndexError("%i document(s) failed to index." % len(errors), errors)
elasticsearch.helpers.errors.BulkIndexError: ('2 document(s) failed to index.', [{'index': {'_index': 'companies_index', '_type': '_doc', '_id': '', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'if _id is specified it must not be empty'}, 'data': {'id': '11c716f2-48ee-44fc-a7a4-c3398e286ae8', 'name': 'Test company', 'website': 'test.com', '_meta': {}}}}, {'index': {'_index': 'companies_index', '_type': '_doc', '_id': '', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'if _id is specified it must not be empty'}, 'data': {'id': '1e0c0b21-0386-439a-9639-68e5e5f4d228', 'name': 'Everest engineering', 'website': 'everest.engineering', '_meta': {}}}}])
 0:00:01.411122 (1.41 sec)
Traceback (most recent call last):
  File "/usr/local/bin/pgsync", line 7, in <module>
    sync.main()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pgsync/sync.py", line 1111, in main
    sync.pull()
  File "/usr/local/lib/python3.9/site-packages/pgsync/sync.py", line 975, in pull
    self.sync(txmin=txmin, txmax=txmax)
  File "/usr/local/lib/python3.9/site-packages/pgsync/sync.py", line 826, in sync
    self.es.bulk(self.index, docs)
  File "/usr/local/lib/python3.9/site-packages/pgsync/elastichelper.py", line 82, in bulk
    for _ in parallel_bulk(
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/helpers/actions.py", line 454, in parallel_bulk
    for result in pool.imap(
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/helpers/actions.py", line 455, in <lambda>
    lambda bulk_chunk: list(
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/helpers/actions.py", line 246, in _process_bulk_chunk
    for item in gen:
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/helpers/actions.py", line 185, in _process_bulk_chunk_success
    raise BulkIndexError("%i document(s) failed to index." % len(errors), errors)
elasticsearch.helpers.errors.BulkIndexError: ('2 document(s) failed to index.', [{'index': {'_index': 'companies_index', '_type': '_doc', '_id': '', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'if _id is specified it must not be empty'}, 'data': {'id': '11c716f2-48ee-44fc-a7a4-c3398e286ae8', 'name': 'Test company', 'website': 'test.com', '_meta': {}}}}, {'index': {'_index': 'companies_index', '_type': '_doc', '_id': '', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'if _id is specified it must not be empty'}, 'data': {'id': '1e0c0b21-0386-439a-9639-68e5e5f4d228', 'name': 'Everest engineering', 'website': 'everest.engineering', '_meta': {}}}}])
`

**Comment by toluaina** [comment]
This is happening because one or more of your tables does not have a primary key defined.
All tables in your schema.json require a primary key
Closing this as there has been no activity in a while.
